// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkGem6fi_ErHTB55aGJ2aa2kCgKnvM6QY',
    appId: '1:80391256079:web:7de72389d7cb5c2fca0b7a',
    messagingSenderId: '80391256079',
    projectId: 'unipathnotifications',
    authDomain: 'unipathnotifications.firebaseapp.com',
    storageBucket: 'unipathnotifications.firebasestorage.app',
    measurementId: 'G-PVSQX23R0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhFjod_7XiVWc4EC8pBIoUKxTqKhsQz0',
    appId: '1:80391256079:android:031027b3c325acaeca0b7a',
    messagingSenderId: '80391256079',
    projectId: 'unipathnotifications',
    storageBucket: 'unipathnotifications.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzMnPlhTeHuN_xlkXK4hQo-k65SmDajKQ',
    appId: '1:80391256079:ios:c702adfacadad606ca0b7a',
    messagingSenderId: '80391256079',
    projectId: 'unipathnotifications',
    storageBucket: 'unipathnotifications.firebasestorage.app',
    iosBundleId: 'com.example.germanyTravel',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzMnPlhTeHuN_xlkXK4hQo-k65SmDajKQ',
    appId: '1:80391256079:ios:c702adfacadad606ca0b7a',
    messagingSenderId: '80391256079',
    projectId: 'unipathnotifications',
    storageBucket: 'unipathnotifications.firebasestorage.app',
    iosBundleId: 'com.example.germanyTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkGem6fi_ErHTB55aGJ2aa2kCgKnvM6QY',
    appId: '1:80391256079:web:cad4f6fcaa3e98d4ca0b7a',
    messagingSenderId: '80391256079',
    projectId: 'unipathnotifications',
    authDomain: 'unipathnotifications.firebaseapp.com',
    storageBucket: 'unipathnotifications.firebasestorage.app',
    measurementId: 'G-G5S9SVBMER',
  );
}
