# generate_sql.ps1
# Transforms scraped BA API data into SQL INSERT statements for Supabase

$scriptDir = $PSScriptRoot
$outputDir = Join-Path $scriptDir "output"

# Read scraped data
$universities = Get-Content -Path (Join-Path $outputDir "universities.json") -Encoding UTF8 | ConvertFrom-Json
$programmes = Get-Content -Path (Join-Path $outputDir "programmes.json") -Encoding UTF8 | ConvertFrom-Json

Write-Output "Loaded $($universities.Count) universities, $($programmes.Count) programmes"

# Escape single quotes for SQL
function Escape-Sql([string]$s) {
    if ([string]::IsNullOrEmpty($s)) { return "NULL" }
    return "'" + $s.Replace("'", "''").Replace("`r`n", "\n").Replace("`n", "\n").Replace("`r", "") + "'"
}

function Escape-SqlText([string]$s) {
    if ([string]::IsNullOrEmpty($s)) { return "NULL" }
    # Strip HTML tags for cleaner text
    $plain = $s -replace '<[^>]+>', ''
    $plain = $plain -replace '&hellip;', '...'
    $plain = $plain -replace '&amp;', '&'
    $plain = $plain -replace '&quot;', '"'
    $plain = $plain -replace '&lt;', '<'
    $plain = $plain -replace '&gt;', '>'
    $plain = $plain -replace '\s+', ' '
    $plain = $plain.Trim()
    if ([string]::IsNullOrEmpty($plain)) { return "NULL" }
    # Truncate very long descriptions (Postgres TEXT can handle it, but keep reasonable)
    if ($plain.Length -gt 2000) { $plain = $plain.Substring(0, 2000) + "..." }
    return "'" + $plain.Replace("'", "''") + "'"
}

# Build a mapping from banId to sequential university ID
$uniIdMap = @{}
$uniIndex = 0
foreach ($u in $universities) {
    $uniIndex++
    $uniIdMap[$u.banId.ToString()] = $uniIndex
}

# Generate SQL
$sqlLines = @()
$sqlLines += "-- Generated by scrape_ba_api.ps1 - Bundesagentur für Arbeit data"
$sqlLines += "-- $($universities.Count) universities, $($programmes.Count) programmes"
$sqlLines += ""
$sqlLines += "-- ============================================================"
$sqlLines += "-- UNIVERSITIES"
$sqlLines += "-- ============================================================"
$sqlLines += ""

$uniIndex = 0
foreach ($u in $universities) {
    $uniIndex++
    $name = Escape-Sql $u.name
    $city = Escape-Sql $u.city
    $state = Escape-Sql $u.state
    $street = Escape-Sql $u.street
    $postalCode = Escape-Sql $u.postalCode
    $country = Escape-Sql "Germany"
    $logoUrl = if ($u.logoUrl) { Escape-Sql $u.logoUrl } else { "NULL" }
    $lat = if ($u.lat -ne 0) { $u.lat.ToString().Replace(',', '.') } else { "NULL" }
    $lon = if ($u.lon -ne 0) { $u.lon.ToString().Replace(',', '.') } else { "NULL" }
    $uniType = Escape-Sql $u.type
    $banId = Escape-Sql $u.banId.ToString()
    $location = Escape-Sql "$($u.city), $($u.state)"
    
    $sqlLines += "INSERT INTO public.universities (id, name, country, location, city, state, street, postal_code, logo_url, lat, lon, university_type, ba_ban_id) VALUES ($uniIndex, $name, $country, $location, $city, $state, $street, $postalCode, $logoUrl, $lat, $lon, $uniType, $banId) ON CONFLICT (id) DO NOTHING;"
}

$sqlLines += ""
$sqlLines += "-- ============================================================"
$sqlLines += "-- UNIVERSITY PROGRAMS"
$sqlLines += "-- ============================================================"
$sqlLines += ""

$progIndex = 0
$batchSize = 500
$batchLines = @()
$totalBatches = 0

foreach ($p in $programmes) {
    $progIndex++
    $uniId = $uniIdMap[$p.universityBanId.ToString()]
    if (-not $uniId) {
        Write-Warning "No university mapping for banId $($p.universityBanId) (programme: $($p.name))"
        continue
    }
    
    $name = Escape-Sql $p.name
    $degreeType = Escape-Sql $p.degreeType
    $major = if ($p.subjects -and $p.subjects.Count -gt 0) { Escape-Sql $p.subjects[0] } else { "NULL" }
    $description = Escape-SqlText $p.description
    $studyMode = Escape-Sql $p.studyMode
    $city = Escape-Sql $p.city
    $state = Escape-Sql $p.state
    $hasDual = if ($p.hasDualOption) { "TRUE" } else { "FALSE" }
    $lat = if ($p.lat -ne 0) { $p.lat.ToString().Replace(',', '.') } else { "NULL" }
    $lon = if ($p.lon -ne 0) { $p.lon.ToString().Replace(',', '.') } else { "NULL" }
    $baProgId = Escape-Sql $p.id.ToString()
    
    # Map degree type ID to our format
    $degreeTypeSimple = "Bachelor"
    if ($p.degreeTypeId -eq 10) { $degreeTypeSimple = "Master" }
    if ($p.degreeTypeId -eq 3) { $degreeTypeSimple = "Diplom" }
    if ($p.degreeTypeId -eq 12) { $degreeTypeSimple = "Staatsexamen" }
    
    $line = "INSERT INTO public.university_programs (university_id, program_name, degree_type, major, description, study_mode, city, state, has_dual_option, lat, lon, ba_program_id) VALUES ($uniId, $name, $(Escape-Sql $degreeTypeSimple), $major, $description, $studyMode, $city, $state, $hasDual, $lat, $lon, $baProgId) ON CONFLICT DO NOTHING;"
    $batchLines += $line
    
    if ($batchLines.Count -ge $batchSize) {
        $totalBatches++
        $sqlLines += "-- Batch $totalBatches"
        $sqlLines += $batchLines
        $sqlLines += ""
        $batchLines = @()
    }
}

# Flush remaining
if ($batchLines.Count -gt 0) {
    $totalBatches++
    $sqlLines += "-- Batch $totalBatches"
    $sqlLines += $batchLines
    $sqlLines += ""
}

$sqlLines += ""
$sqlLines += "-- ============================================================"
$sqlLines += "-- Fix sequences"
$sqlLines += "-- ============================================================"
$sqlLines += "SELECT setval(pg_get_serial_sequence('universities', 'id'), COALESCE((SELECT MAX(id) FROM universities), 0) + 1, false);"
$sqlLines += "SELECT setval(pg_get_serial_sequence('university_programs', 'id'), COALESCE((SELECT MAX(id) FROM university_programs), 0) + 1, false);"

$sqlContent = $sqlLines -join "`r`n"

# Save SQL
$sqlPath = Join-Path $outputDir "import_data.sql"
$sqlContent | Set-Content -Path $sqlPath -Encoding UTF8
Write-Output "SQL written to: $sqlPath"
Write-Output "Total universities: $uniIndex"
Write-Output "Total programmes attempted: $progIndex"
Write-Output "Total batches: $totalBatches"
Write-Output "File size: $((Get-Item $sqlPath).Length / 1MB) MB"
