-- Add columns for new settings features
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_toefl BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS toefl_score NUMERIC DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS nationality TEXT DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS preferred_cities TEXT[] DEFAULT '{}';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS budget_range TEXT DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_moi BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS intake TEXT DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS language_preference TEXT DEFAULT '';
