import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'appTitle': 'UniPath',
      'home': 'Home',
      'search': 'Search',
      'applications': 'Applications',
      'profile': 'Profile',
      'settings': 'Settings',
      'accountSettings': 'Account Settings',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'save': 'Save',
      'edit': 'Edit',
      'cancel': 'Cancel',
      'deleteAccount': 'Delete Account',
      'deleteAccountWarning': 'Are you sure? This action cannot be undone.',
      'yesDelete': 'Yes, Delete',
      'name': 'Name',
      'email': 'Email',
      'gpa': 'GPA',
      'nationality': 'Nationality',
      'preferredCities': 'Preferred Cities',
      'budgetRange': 'Budget Range',
      'notifications': 'Notifications',
      'deadlineReminders': 'Deadline Reminders',
      'generalNotifications': 'General Notifications',
      'profileCompleteness': 'Profile Completeness',
      'matchScore': 'Your Match Score',
      'goodChance': 'Good Chance',
      'strongMatch': 'Strong Match',
      'fairMatch': 'Fair Match',
      'weakMatch': 'Weak Match',
      'notRecommended': 'Not Recommended',
      'excellentMatch': 'Excellent Match',
      'recommendedForYou': 'Recommended for you',
      'seeAll': 'See all',
      'findPrograms': 'Find Programs',
      'aiAdvisor': 'AI Advisor',
      'sopAssistant': 'SOP Assistant',
      'cvBuilder': 'CV Builder',
      'noIelts': 'No IELTS',
      'englishProgram': 'English Program',
      'tuition': 'Tuition',
      'location': 'Location',
      'intake': 'Intake',
      'degree': 'Degree',
      'major': 'Major',
      'languageOfInstruction': 'Language of Instruction',
      'ielts': 'IELTS',
      'toefl': 'TOEFL',
      'moi': 'MOI',
      'uploadDocuments': 'Upload Documents',
      'aiReview': 'AI Document Review',
      'aiTips': 'AI Improvement Tips',
      'remainingUses': 'Remaining uses:',
      'premiumFeature': 'Premium Feature',
      'premiumDescription':
          'This is a premium feature. Please upgrade your plan.',
      // 'goToPayment': 'Go to Payment', // removed - no payment screen
      'settingsSaved': 'Settings saved successfully!',
      'noDocuments': 'No documents uploaded yet',
      'checkRequirements': 'Check the Requirements tab above',
      'overBudget': 'Over Budget',
      'withinBudget': 'Within Budget',
      'preferredCity': 'Preferred City',
      'personalInfo': 'Personal Info',
      'academicProfile': 'Academic Profile',
      'preferences': 'Preferences',
      'languageCertificate': 'Language Certificate',
      'appSettings': 'App Settings',
      'fieldOfStudy': 'Field of Study',
      'degreeLevel': 'Degree Level',
      'studyLanguage': 'Study Language',
      'targetIntake': 'Target Intake',
      'gpaScale': 'GPA Scale',
      'all': 'All',
      'saved': 'Saved',
      'preparing': 'Preparing',
      'applied': 'Applied',
      'waiting': 'Waiting',
      'accepted': 'Accepted',
      'deadline': 'Deadline',
      'docs': 'Docs',
      'chance': 'Chance',
      'expired': 'Expired',
      'today': 'Today',
      'inDays': 'In %d days',
      'viewDetails': 'View Details',
      'searchPrograms': 'Search programs or universities...',
      'studyInGermany': 'Study in Germany',
      'upcomingDeadlines': 'Upcoming Deadlines',
      'yourMatchAverage': 'Your Match Average',
      'inTheNext30Days': 'In the next 30 days',
      'high': 'High',
      'medium': 'Medium',
      'requirementsChecklist': 'Requirements Checklist',
      'close': 'Close',
      'noApplicationsFound': 'No applications found',
      'programsMatch': 'Programs Match Your Profile',
      'loadingMore': 'Loading more...',
      'seenAllPrograms': "You've seen all available programs!",
      'universitiesFound': 'Universities Found',
      'retry': 'Retry',
      'searchForCourses': 'Search for courses or universities...',
      'filters': 'Filters',
      'clearAll': 'Clear All',
      'ieltsRequired': 'IELTS Required',
      'moiAccepted': 'MOI Accepted',
      'maxTuitionPerYear': 'Max Tuition / Year',
      'instructionLanguage': 'Instruction Language',
      'locationCity': 'Location / City',
      'allLocations': 'All Locations',
      'logout': 'Logout',
      'login': 'Login',
      'register': 'Register',
      'welcomeBack': 'Welcome Back!',
      'loginSubtitle': 'Login to continue your study abroad journey',
      'emailOrUsername': 'Email address or Username',
      'enterEmailOrUsername': 'Please enter your email or username',
      'enterPassword': 'Please enter your password',
      'passwordMinLength': 'Password must be at least 6 characters',
      'forgotPassword': 'Forgot password?',
      'rememberMe': 'Remember me',
      'or': 'or',
      'noAccount': "Don't have an account? ",
      'createAccount': 'Create Account',
      'registerSubtitle': 'Join UniPath to achieve your dreams in Germany.',
      'username': 'Username',
      'enterUsername': 'Please enter a username',
      'usernameMinLength': 'Username must be at least 3 characters',
      'phoneOptional': 'Phone (optional)',
      'enterEmailAddress': 'Please enter your email address',
      'enterValidEmail': 'Please enter a valid email address',
      'enterPasswordRegister': 'Please enter a password',
      'passwordMinLengthRegister': 'Password must be at least 6 characters',
      'confirmPassword': 'Confirm password',
      'confirmYourPassword': 'Please confirm your password',
      'passwordsNotMatch': 'Passwords do not match',
      'alreadyHaveAccount': 'Already have an account? ',
      'overview': 'Overview',
      'curriculum': 'Curriculum',
      'checklist': 'Checklist',
      'notes': 'Notes',
      'free': 'Free',
      'nonRefundable': 'Non-refundable',
      'freeProgram': 'Free Program',
      'perYear': 'Per Year',
      'noDeadline': 'No deadline',
      'notAvailable': 'N/A',
      'aboutUniversity': 'About the University',
      'descriptionPlaceholder': 'Detailed description about the university will be available soon.',
      'readMore': 'Read more',
      'programCurriculum': 'Program Curriculum',
      'noDetails': 'No details',
      'noCurriculumData': 'No curriculum data.',
      'filterAiRecommended': 'Filter AI Recommended tracks for your profile',
      'askUniPathAi': 'Ask UniPath AI',
      'welcomeTitle': "Let's personalize\nyour experience",
      'welcomeSubtitle':
          'We\'ll ask you a few questions to find the best universities and programs for you.',
      'intakeHeading': 'When do you want to\nstart studying?',
      'studyLevelHeading': 'What level of study are\nyou looking for?',
      'studyLevelSubtitle': 'You can select your target degree',
      'majorHeading': 'Select your major\nfield of study',
      'majorSubtitle':
          'Choose the discipline that matches your academic background',
      'langHeading': 'Your Language\nPreference',
      'langSubtitle': 'Select the language you wish to study in.',
      'ieltsHeading': 'English Language\nProficiency',
      'ieltsSubtitle': 'Which English proficiency test do you have?',
      'ieltsScoreHeading': 'What is your overall\nIELTS band score?',
      'ieltsScoreSubtitle':
          'Drag the slider to match your certificate score',
      'moiHeading': 'MOI Confirmation',
      'moiSubtitle':
          'Do you confirm that your previous education was taught entirely in English?',
      'moiConfirmYes': 'Yes, I confirm',
      'moiConfirmYesSub': 'My degree was taught completely in English',
      'moiConfirmNo': 'No, go back',
      'moiConfirmNoSub': 'Choose a different option',
      'tokenHeading': 'Authentication Token',
      'tokenSubtitle':
          'Enter your authentication token if you have one (Optional)',
      'tokenLabel': 'Token (Optional)',
      'tokenHint': 'Enter your token here...',
      'noneHeading': 'No English Certificate',
      'noneSubtitle':
          'You selected that you don\'t have any English certificate. Some programs may require one.',
      'noneNote': 'Note',
      'noneNoteBody':
          'You can still apply to programs that don\'t require English certificates or accept MOI.',
      'gpaHeading': 'Your Academic\nPerformance',
      'gpaSubtitle': 'Enter your cumulative GPA or percentage',
      'gpaScaleLabel': 'GPA Scale System',
      'gpaEarnedLabel': 'Earned GPA / Score',
      'gpaHint4': 'Enter a value between 0.0 and 4.0',
      'gpaHint5': 'Enter a value between 0.0 and 5.0',
      'gpaHint100': 'Enter your overall percentage (0 - 100)',
      'budgetHeading': 'What is your tuition\nbudget per year?',
      'budgetSubtitle': 'Select the maximum tuition fees you can afford',
      'goalsHeading': 'What are your primary\nstudy goals?',
      'goalsSubtitle': 'Select all that apply to your future plans',
      'btnGetStarted': "Let's Get Started \u2192",
      'btnLooksGood': 'Looks Good! \u2192',
      'btnContinue': 'Continue',
      'valIntake': 'Please select when you want to start studying',
      'valStudyLevel': 'Please select your study level',
      'valMajor': 'Please select your field of interest',
      'valLanguage': 'Please select your language preference',
      'valTestType': 'Please select your English proficiency test',
      'valScore': 'Please enter your test score',
      'valGpa': 'Please enter your GPA',
      'valGpaScale': 'Please select your GPA scale',
      'valMoiConfirm': 'Please confirm that you have an MOI letter',
      'valBudget': 'Please select your budget range',
      'notesSaved': 'Notes saved successfully!',
      'errorSavingNotes': 'Error saving notes',
      'monthlyLimitReached': 'Monthly limit reached (10 uses). Upgrade for unlimited!',
      // 'paymentComingSoon': 'Payment screen coming soon', // removed
      'noDocumentsUploaded': 'No documents uploaded yet. Upload your documents from the checklist above (Transcripts, CV, SOP, Certificate).',
      'profileDataNotLoaded': 'Profile data not loaded yet. Try again.',
      'comingSoon': 'Coming soon',
      'welcomeAccountCreated': 'Account created successfully! Welcome to UniPath!',
      'welcomeBackLogin': 'Welcome back! Successfully logged in.',
      'loggedOutSuccess': 'Logged out successfully!',
      'uploadDescription': 'Files uploaded here will automatically be used for all your German university applications.',
      'reviewingDocuments': 'Reviewing Your Documents',
      'starting': 'Starting...',
      'downloadLabel': 'Downloading',
      'analyzeLabel': 'Analyzing',
      'recommendationsLabel': 'Getting recommendations for',
      'cachedLabel': 'Cached',
      'downloadTimedOut': 'Download timed out. Check your internet connection.',
      'serverReturned': 'Server returned {code}. Try again later.',
      'couldNotDownload': 'Could not download the file. Check your connection.',
      'aiFailed': 'AI analysis failed: {error}',
      'uploadThisDoc': 'Upload this document to get specific feedback.',
      'reviewFailed': 'Failed to review documents. Check your connection.',
      'uploadDocumentTitle': 'Upload Document',
      'pdfFile': 'PDF File',
      'pdfSubtitle': 'Choose a PDF from your device (max 10 MB)',
      'gallery': 'Gallery',
      'gallerySubtitle': 'Pick an image from your gallery',
      'camera': 'Camera',
      'cameraSubtitle': 'Take a photo of your document',
      'fileTooLarge': 'File too large. Maximum size is 20 MB.',
      'resetPassword': 'Reset Password',
      'send': 'Send',
      'passwordResetSent': 'Password reset email sent! Check your inbox.',
      'loginSuccess': 'Welcome back!',
      'registerSuccess': 'Account created successfully!',
      'premium': 'Premium',
      'unlockPremium': 'Unlock Premium',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'lifetime': 'Lifetime',
      'bestValue': 'Best Value',
      'restorePurchases': 'Restore Purchases',
      'payment': 'Payment',
      'premiumActivated': 'Premium activated successfully!',
      'paymentComingSoon': 'Payment integration coming soon!',
      'perMonthShort': '/month',
      'perYearShort': '/year',
      'oneTime': 'One-time',
      'savePercent': 'Save {percent}%',
      'premiumFeatures': 'Premium Features',
      'aiReviewUnlimited': 'AI Document Review (Unlimited)',
      'aiImprovement': 'AI Improvement Suggestions',
      'premiumMatchScore': 'Premium Match Score (20%)',
      'prioritySupport': 'Priority Support',
      'unlimitedAiUses': 'Unlimited AI Uses',
      'goPremium': 'Go Premium',
      'youArePremium': 'You are Premium!',
      'premiumUntil': 'Premium until {date}',
      'unlocked': 'Unlocked',

      // Home AI Tips
      'strongProfile': 'Strong Profile',
      'strongProfileDesc': 'Your profile is a great match! Focus on submitting strong documents (CV, SOP, transcripts) for each application.',
      'polishDocuments': 'Polish Your Documents',
      'polishDocumentsDesc': 'Use the AI Document Generator on each program page to create tailored CVs and motivation letters that highlight your strengths.',
      'trackDeadlines': 'Track Deadlines',
      'trackDeadlinesDesc': 'Enable deadline reminders in Settings to never miss an application window.',
      'boostGpa': 'Boost Your GPA Score',
      'boostGpaDesc': 'Consider retaking courses or highlighting relevant project experience in your SOP to compensate.',
      'languageCert': 'Language Certificate',
      'languageCertDesc': 'Improving your IELTS score or getting an MOI certificate can add significant points to your match score.',
      'refineMajor': 'Refine Your Major',
      'refineMajorDesc': 'Visit Settings to ensure your target major is as specific as possible for better program matching.',
      'completeProfile': 'Complete Your Profile',
      'completeProfileDesc': 'Your profile is incomplete. Adding your GPA, IELTS score, and target major will dramatically improve matching.',
      'getLanguageCertified': 'Get Language Certified',
      'getLanguageCertifiedDesc': 'Most programs require IELTS (6.0+) or MOI. Adding either unlocks 10-15 points in the match score.',
      'pickIntake': 'Pick an Intake',
      'pickIntakeDesc': 'Setting your target intake helps match with programs that align with your timeline.',
      'profileNeeded': 'Profile Needed',
      'profileNeededDesc': 'Set up your academic profile in Settings — GPA, major, degree level, and language preferences.',
      'explorePrograms': 'Explore Programs',
      'exploreProgramsDesc': 'Use the Search tab to find programs. Save interesting ones to see your match score.',
      'visitSettings': 'Visit Settings',
      'visitSettingsDesc': 'Complete all profile fields to unlock personalized AI suggestions for each program.',

      // Profile screen
      'accountAndTools': 'Account & Tools',
      'myDocuments': 'My Documents',
      'cvSopCertificates': 'CV, SOP & Certificates',
      'emailTracking': 'Email Tracking',
      'emailTrackingDesc': 'Auto-detect application status from emails',
      'updateProfilePrefs': 'Update your Profile & Preferences',
      'adminDashboard': 'Admin Dashboard',
      'adminDashboardDesc': 'Manage users, universities & more',
      'signOutOfUnipath': 'Sign out of UniPath',
      'confirmLogout': 'Are you sure you want to log out?',
      'couldNotLoadProfile': 'Could not load profile',
      'ensureLoggedIn': 'Please make sure you are logged in.',

      // Connectivity banner
      'noInternetConnection': 'No internet connection. Some features may not work.',
      'slowConnection': 'Slow connection. Loading may take longer.',
      'connectionRestored': 'Connection restored',

      // Requirements checklist
      'academicTranscripts': 'Academic Transcripts',
      'bachelorCertificate': 'Bachelor Certificate',
      'sopMotivationLetter': 'SOP / Motivation Letter',
      'cvResume': 'CV / Resume',
      'languageCertOptional': 'Language Certificate (IELTS/TOEFL) — Optional',

      // Payment / Paywall
      'pleaseSignInFirst': 'Please sign in first',
      'checkingPaymentStatus': 'Checking payment status...',
      'paymentDelayed': 'Payment received but activation is delayed. It will activate shortly.',

      // AI Generator
      'links': 'Links',
      'failedToGeneratePdf': 'Failed to generate PDF: {error}',
      'fillNameAndBackground': 'Please fill in your name and background.',
      'copiedToClipboard': 'Copied to clipboard!',
      'generateCvSopAi': 'Generate CV / SOP with AI',
      'copy': 'Copy',
      'downloadPdf': 'Download PDF',
      'replaceFile': 'Replace file',
      'cvGenerated': 'CV Generated',
      'motivationLetterGenerated': 'Motivation Letter Generated',

      // Comparison
      'compare': 'Compare',
      'compareUniversities': 'Compare Universities',
      'selectUniversities': 'Select universities to compare',
      'feature': 'Feature',
      'noDeadlines': 'No deadlines on this day',

      // Calendar
      'deadlineCalendar': 'Deadline Calendar',
      'upcomingDeadlinesCount': 'Upcoming Deadlines',

      // Templates
      'documentTemplates': 'Document Templates',
      'cvTemplate': 'CV / Resume - German Style',
      'motivationLetterTemplate': 'Motivation Letter Template',
      'recommendationTemplate': 'Recommendation Letter Request',

      // Dashboard
      'avgMatch': 'Average Match',
      'byStatus': 'Applications by Status',

      // Back
      'pressAgainToExit': 'Press again to exit',
    },
    'ar': {
      'appTitle': 'يوني باث',
      'home': 'الرئيسية',
      'search': 'بحث',
      'applications': 'الطلبات',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'accountSettings': 'إعدادات الحساب',
      'darkMode': 'الوضع الليلي',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'save': 'حفظ',
      'edit': 'تعديل',
      'cancel': 'إلغاء',
      'deleteAccount': 'حذف الحساب',
      'deleteAccountWarning':
          'هل أنت متأكد؟ لا يمكن التراجع عن هذا الإجراء.',
      'yesDelete': 'نعم، احذف',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'gpa': 'المعدل',
      'nationality': 'الجنسية',
      'preferredCities': 'المدن المفضلة',
      'budgetRange': 'نطاق الميزانية',
      'notifications': 'الإشعارات',
      'deadlineReminders': 'تذكيرات المواعيد',
      'generalNotifications': 'الإشعارات العامة',
      'profileCompleteness': 'اكتمال الملف',
      'matchScore': 'نسبة التطابق',
      'goodChance': 'فرصة جيدة',
      'strongMatch': 'تطابق قوي',
      'fairMatch': 'تطابق متوسط',
      'weakMatch': 'تطابق ضعيف',
      'notRecommended': 'غير موصى به',
      'excellentMatch': 'تطابق ممتاز',
      'recommendedForYou': 'موصى به لك',
      'seeAll': 'عرض الكل',
      'findPrograms': 'البحث عن برامج',
      'aiAdvisor': 'المستشار الذكي',
      'sopAssistant': 'مساعد البيان الشخصي',
      'cvBuilder': 'بناء السيرة الذاتية',
      'noIelts': 'بدون آيلتس',
      'englishProgram': 'برنامج إنجليزي',
      'tuition': 'الرسوم',
      'location': 'الموقع',
      'intake': 'موعد التقديم',
      'degree': 'الدرجة العلمية',
      'major': 'التخصص',
      'languageOfInstruction': 'لغة التدريس',
      'ielts': 'آيلتس',
      'toefl': 'توفل',
      'moi': 'شهادة اللغة',
      'uploadDocuments': 'رفع المستندات',
      'aiReview': 'مراجعة المستندات بالذكاء الاصطناعي',
      'aiTips': 'نصائح التحسين بالذكاء الاصطناعي',
      'remainingUses': 'الاستخدامات المتبقية:',
      'premiumFeature': 'ميزة مدفوعة',
      'premiumDescription': 'هذه ميزة مدفوعة. يرجى ترقية باقتك.',
      // 'goToPayment': 'اذهب للدفع', // removed - no payment screen
      'settingsSaved': 'تم حفظ الإعدادات بنجاح!',
      'noDocuments': 'لم يتم رفع أي مستندات بعد',
      'checkRequirements': 'تفقد قسم المتطلبات أعلاه',
      'overBudget': 'فوق الميزانية',
      'withinBudget': 'ضمن الميزانية',
      'preferredCity': 'المدينة المفضلة',
      'personalInfo': 'المعلومات الشخصية',
      'academicProfile': 'الملف الأكاديمي',
      'preferences': 'التفضيلات',
      'languageCertificate': 'شهادة اللغة',
      'appSettings': 'إعدادات التطبيق',
      'fieldOfStudy': 'مجال الدراسة',
      'degreeLevel': 'المستوى الدراسي',
      'studyLanguage': 'لغة الدراسة',
      'targetIntake': 'موعد التقديم',
      'gpaScale': 'مقياس المعدل',
      'all': 'الكل',
      'saved': 'محفوظ',
      'preparing': 'قيد التحضير',
      'applied': 'مقدم',
      'waiting': 'قيد الانتظار',
      'accepted': 'مقبول',
      'deadline': 'آخر موعد',
      'docs': 'المستندات',
      'chance': 'الفرصة',
      'expired': 'منتهي',
      'today': 'اليوم',
      'inDays': 'بعد %d أيام',
      'viewDetails': 'عرض التفاصيل',
      'searchPrograms': 'ابحث عن برامج أو جامعات...',
      'studyInGermany': 'ادرس في ألمانيا',
      'upcomingDeadlines': 'المواعيد القادمة',
      'yourMatchAverage': 'متوسط التطابق',
      'inTheNext30Days': 'في الـ 30 يوماً القادمة',
      'high': 'عالية',
      'medium': 'متوسطة',
      'requirementsChecklist': 'قائمة المتطلبات',
      'close': 'إغلاق',
      'noApplicationsFound': 'لا توجد طلبات',
      'programsMatch': 'برنامج تطابق ملفك',
      'loadingMore': 'جارٍ التحميل...',
      'seenAllPrograms': 'لقد رأيت جميع البرامج المتاحة!',
      'universitiesFound': 'جامعة موجودة',
      'retry': 'إعادة المحاولة',
      'searchForCourses': 'ابحث عن courses أو جامعات...',
      'filters': 'تصفية',
      'clearAll': 'مسح الكل',
      'ieltsRequired': 'مطلوب آيلتس',
      'moiAccepted': 'مقبول شهادة لغة',
      'maxTuitionPerYear': 'الحد الأقصى للرسوم / سنة',
      'instructionLanguage': 'لغة التدريس',
      'locationCity': 'الموقع / المدينة',
      'allLocations': 'جميع المواقع',
      'logout': 'تسجيل الخروج',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'welcomeBack': 'مرحباً بعودتك!',
      'loginSubtitle': 'سجل الدخول لمواصلة رحلة دراستك في الخارج',
      'emailOrUsername': 'البريد الإلكتروني أو اسم المستخدم',
      'enterEmailOrUsername': 'الرجاء إدخال البريد الإلكتروني أو اسم المستخدم',
      'enterPassword': 'الرجاء إدخال كلمة المرور',
      'passwordMinLength': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'rememberMe': 'تذكرني',
      'or': 'أو',
      'noAccount': 'ليس لديك حساب؟ ',
      'createAccount': 'إنشاء حساب',
      'registerSubtitle': 'انضم إلى يوني باث لتحقيق أحلامك في ألمانيا.',
      'username': 'اسم المستخدم',
      'enterUsername': 'الرجاء إدخال اسم المستخدم',
      'usernameMinLength': 'يجب أن يكون اسم المستخدم 3 أحرف على الأقل',
      'phoneOptional': 'الهاتف (اختياري)',
      'enterEmailAddress': 'الرجاء إدخال عنوان البريد الإلكتروني',
      'enterValidEmail': 'الرجاء إدخال بريد إلكتروني صحيح',
      'enterPasswordRegister': 'الرجاء إدخال كلمة المرور',
      'passwordMinLengthRegister': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'confirmPassword': 'تأكيد كلمة المرور',
      'confirmYourPassword': 'الرجاء تأكيد كلمة المرور',
      'passwordsNotMatch': 'كلمة المرور غير متطابقة',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟ ',
      'overview': 'نظرة عامة',
      'curriculum': 'المنهج',
      'checklist': 'قائمة المتطلبات',
      'notes': 'ملاحظات',
      'free': 'مجاني',
      'nonRefundable': 'غير قابل للاسترداد',
      'freeProgram': 'برنامج مجاني',
      'perYear': 'في السنة',
      'noDeadline': 'لا يوجد موعد',
      'notAvailable': 'غير متاح',
      'aboutUniversity': 'عن الجامعة',
      'descriptionPlaceholder': 'الوصف التفصيلي عن الجامعة سيكون متاحاً قريباً.',
      'readMore': 'اقرأ المزيد',
      'programCurriculum': 'المنهج الدراسي',
      'noDetails': 'لا توجد تفاصيل',
      'noCurriculumData': 'لا توجد بيانات منهج.',
      'filterAiRecommended': 'تصفية المسارات الموصى بها بالذكاء الاصطناعي لملفك',
      'askUniPathAi': 'اسأل يوني باث',
      'welcomeTitle': 'دعنا نخصص\nتجربتك',
      'welcomeSubtitle':
          'سنطرح عليك بعض الأسئلة للعثور على أفضل الجامعات والبرامج المناسبة لك.',
      'intakeHeading': 'متى تريد أن\nتبدأ الدراسة؟',
      'studyLevelHeading': 'ما المستوى الدراسي\nالذي تبحث عنه؟',
      'studyLevelSubtitle': 'يمكنك اختيار الدرجة المستهدفة',
      'majorHeading': 'اختر تخصصك\nالدراسي',
      'majorSubtitle': 'اختر المجال الذي يتناسب مع خلفيتك الأكاديمية',
      'langHeading': 'تفضيل\nاللغة',
      'langSubtitle': 'اختر اللغة التي ترغب في الدراسة بها.',
      'ieltsHeading': 'اختبار اللغة\nالإنجليزية',
      'ieltsSubtitle': 'ما هو اختبار اللغة الإنجليزية الذي لديك؟',
      'ieltsScoreHeading': 'ما هي درجة\nالآيلتس الإجمالية لديك؟',
      'ieltsScoreSubtitle': 'اسحب الشريط لمطابقة درجة شهادتك',
      'moiHeading': 'تأكيد شهادة اللغة',
      'moiSubtitle':
          'هل تؤكد أن تعليمك السابق كان باللغة الإنجليزية بالكامل؟',
      'moiConfirmYes': 'نعم، أؤكد',
      'moiConfirmYesSub': 'دراستي كانت باللغة الإنجليزية بالكامل',
      'moiConfirmNo': 'لا، عد للخلف',
      'moiConfirmNoSub': 'اختيار خيار آخر',
      'tokenHeading': 'رمز التوثيق',
      'tokenSubtitle': 'أدخل رمز التوثيق إذا كان لديك (اختياري)',
      'tokenLabel': 'الرمز (اختياري)',
      'tokenHint': 'أدخل الرمز هنا...',
      'noneHeading': 'لا توجد شهادة لغة',
      'noneSubtitle':
          'لقد اخترت أنه ليس لديك شهادة لغة إنجليزية. بعض البرامج قد تتطلب واحدة.',
      'noneNote': 'ملاحظة',
      'noneNoteBody':
          'لا يزال بإمكانك التقدم للبرامج التي لا تتطلب شهادات لغة إنجليزية أو تقبل MOI.',
      'gpaHeading': 'أدائك\nالأكاديمي',
      'gpaSubtitle': 'أدخل معدلك التراكمي أو النسبة المئوية',
      'gpaScaleLabel': 'نظام مقياس المعدل',
      'gpaEarnedLabel': 'المعدل / الدرجة',
      'gpaHint4': 'أدخل قيمة بين 0.0 و 4.0',
      'gpaHint5': 'أدخل قيمة بين 0.0 و 5.0',
      'gpaHint100': 'أدخل النسبة المئوية الإجمالية (0 - 100)',
      'budgetHeading': 'ما هي ميزانية\nالرسوم الدراسية سنوياً؟',
      'budgetSubtitle': 'اختر الحد الأقصى للرسوم الذي يمكنك تحمله',
      'goalsHeading': 'ما هي أهدافك\nالدراسية الأساسية؟',
      'goalsSubtitle': 'اختر كل ما ينطبق على خططك المستقبلية',
      'btnGetStarted': 'لنبدأ \u2192',
      'btnLooksGood': 'يبدو جيداً! \u2192',
      'btnContinue': 'متابعة',
      'valIntake': 'الرجاء اختيار موعد بدء الدراسة',
      'valStudyLevel': 'الرجاء اختيار المستوى الدراسي',
      'valMajor': 'الرجاء اختيار مجال الاهتمام',
      'valLanguage': 'الرجاء اختيار تفضيل اللغة',
      'valTestType': 'الرجاء اختيار اختبار اللغة الإنجليزية',
      'valScore': 'الرجاء إدخال درجة الاختبار',
      'valGpa': 'الرجاء إدخال المعدل',
      'valGpaScale': 'الرجاء اختيار مقياس المعدل',
      'valMoiConfirm': 'الرجاء تأكيد أن لديك خطاب MOI',
      'valBudget': 'الرجاء اختيار نطاق الميزانية',
      'notesSaved': 'تم حفظ الملاحظات بنجاح!',
      'errorSavingNotes': 'خطأ في حفظ الملاحظات',
      'monthlyLimitReached': 'لقد وصلت للحد الشهري (10 استخدامات). قم بالترقية للاستخدام غير المحدود!',
      // 'paymentComingSoon': 'شاشة الدفع قريباً', // removed
      'noDocumentsUploaded': 'لم يتم رفع أي مستندات بعد. قم برفع مستنداتك من قائمة المتطلبات أعلاه (كشف الدرجات، السيرة الذاتية، بيان الغرض، الشهادة).',
      'profileDataNotLoaded': 'بيانات الملف الشخصي لم يتم تحميلها بعد. حاول مرة أخرى.',
      'comingSoon': 'قريباً',
      'welcomeAccountCreated': 'تم إنشاء الحساب بنجاح! مرحباً بك في يوني باث!',
      'welcomeBackLogin': 'مرحباً بعودتك! تم تسجيل الدخول بنجاح.',
      'loggedOutSuccess': 'تم تسجيل الخروج بنجاح!',
      'uploadDescription': 'الملفات التي يتم رفعها هنا ستُستخدم تلقائياً في جميع طلبات التقديم للجامعات الألمانية.',
      'reviewingDocuments': 'مراجعة مستنداتك',
      'starting': 'جارٍ البدء...',
      'downloadLabel': 'جارٍ التحميل',
      'analyzeLabel': 'جارٍ التحليل',
      'recommendationsLabel': 'جارٍ الحصول على التوصيات لـ',
      'cachedLabel': 'مخبأ',
      'downloadTimedOut': 'انتهت مهلة التحميل. تحقق من اتصالك بالإنترنت.',
      'serverReturned': 'الخادم أرجع {code}. حاول مرة أخرى لاحقاً.',
      'couldNotDownload': 'تعذر تحميل الملف. تحقق من اتصالك.',
      'aiFailed': 'فشل تحليل الذكاء الاصطناعي: {error}',
      'uploadThisDoc': 'قم برفع هذا المستند للحصول على تقييم محدد.',
      'reviewFailed': 'فشلت مراجعة المستندات. تحقق من اتصالك.',
      'uploadDocumentTitle': 'رفع مستند',
      'pdfFile': 'ملف PDF',
      'pdfSubtitle': 'اختر PDF من جهازك (الحد الأقصى 10 ميجابايت)',
      'gallery': 'المعرض',
      'gallerySubtitle': 'اختر صورة من معرض الصور',
      'camera': 'الكاميرا',
      'cameraSubtitle': 'التقط صورة للمستند',
      'fileTooLarge': 'الملف كبير جداً. الحد الأقصى 20 ميجابايت.',
      'resetPassword': 'إعادة تعيين كلمة المرور',
      'send': 'إرسال',
      'passwordResetSent': 'تم إرسال بريد إعادة تعيين كلمة المرور! تحقق من بريدك الوارد.',
      'loginSuccess': 'مرحباً بعودتك!',
      'registerSuccess': 'تم إنشاء الحساب بنجاح!',
      'premium': 'بريميوم',
      'unlockPremium': 'فتح البريميوم',
      'monthly': 'شهري',
      'yearly': 'سنوي',
      'lifetime': 'مدى الحياة',
      'bestValue': 'أفضل قيمة',
      'restorePurchases': 'استعادة المشتريات',
      'payment': 'الدفع',
      'premiumActivated': 'تم تفعيل البريميوم بنجاح!',
      'paymentComingSoon': 'قريباً نظام الدفع!',
      'perMonthShort': '/شهر',
      'perYearShort': '/سنة',
      'oneTime': 'مرة واحدة',
      'savePercent': 'وفر {percent}%',
      'premiumFeatures': 'ميزات البريميوم',
      'aiReviewUnlimited': 'مراجعة المستندات بالذكاء الاصطناعي (غير محدود)',
      'aiImprovement': 'اقتراحات التحسين بالذكاء الاصطناعي',
      'premiumMatchScore': 'نسبة التطابق المميزة (20%)',
      'prioritySupport': 'دعم ذو أولوية',
      'unlimitedAiUses': 'استخدام غير محدود للذكاء الاصطناعي',
      'goPremium': 'اشتراك بريميوم',
      'youArePremium': 'أنت مشترك في البريميوم!',
      'premiumUntil': 'بريميوم حتى {date}',
      'unlocked': 'مفتوح',

      // Home AI Tips
      'strongProfile': 'ملف قوي',
      'strongProfileDesc': 'ملفك الشخصي ممتاز! ركز على تقديم مستندات قوية (سيرة ذاتية، بيان شخصي، كشوف درجات) لكل طلب.',
      'polishDocuments': 'حسّن مستنداتك',
      'polishDocumentsDesc': 'استخدم مولد المستندات بالذكاء الاصطناعي في صفحة كل برنامج لإنشاء سيرة ذاتية ورسائل تحفيز مخصصة.',
      'trackDeadlines': 'تتبع المواعيد النهائية',
      'trackDeadlinesDesc': 'فعّل تذكيرات المواعيد النهائية في الإعدادات لعدم تفويت أي فرصة تقديم.',
      'boostGpa': 'حسّن معدلك التراكمي',
      'boostGpaDesc': 'فكر في إعادة المواد أو إبراز الخبرات العملية ذات الصلة في بيانك الشخصي.',
      'languageCert': 'شهادة لغة',
      'languageCertDesc': 'تحسين درجة الآيلتس أو الحصول على شهادة MOI يضيف نقاطاً مهمة لنسبة التطابق.',
      'refineMajor': 'حدد تخصصك',
      'refineMajorDesc': 'زر الإعدادات لتحديد تخصصك بدقة أكبر للحصول على تطابق أفضل مع البرامج.',
      'completeProfile': 'أكمل ملفك الشخصي',
      'completeProfileDesc': 'ملفك غير مكتمل. إضافة المعدل، درجة الآيلتس، والتخصص المستهدف سيحسن التطابق بشكل كبير.',
      'getLanguageCertified': 'احصل على شهادة لغة',
      'getLanguageCertifiedDesc': 'معظم البرامج تتطلب آيلتس (6.0+) أو MOI. إضافة أي منهما يفتح 10-15 نقطة في نسبة التطابق.',
      'pickIntake': 'اختر موعد التقديم',
      'pickIntakeDesc': 'تحديد موعد التقديم المستهدف يساعد في إيجاد البرامج المتوافقة مع جدولك الزمني.',
      'profileNeeded': 'الملف الشخصي مطلوب',
      'profileNeededDesc': 'أكمل ملفك الأكاديمي في الإعدادات — المعدل، التخصص، المستوى الدراسي، وتفضيلات اللغة.',
      'explorePrograms': 'استكشف البرامج',
      'exploreProgramsDesc': 'استخدم علامة التبويب "بحث" لإيجاد البرامج. احفظ الم interessante منها لترى نسبة التطابق.',
      'visitSettings': 'زر الإعدادات',
      'visitSettingsDesc': 'أكمل جميع حقول الملف الشخصي لفتح اقتراحات الذكاء الاصطناعي المخصصة لكل برنامج.',

      // Profile screen
      'accountAndTools': 'الحساب والأدوات',
      'myDocuments': 'مستنداتي',
      'cvSopCertificates': 'السيرة الذاتية، البيان الشخصي والشهادات',
      'emailTracking': 'تتبع البريد الإلكتروني',
      'emailTrackingDesc': 'الكشف التلقائي عن حالة الطلب من البريد',
      'updateProfilePrefs': 'تحديث ملفك الشخصي وتفضيلاتك',
      'adminDashboard': 'لوحة التحكم',
      'adminDashboardDesc': 'إدارة المستخدمين، الجامعات والمزيد',
      'signOutOfUnipath': 'تسجيل الخروج من يوني باث',
      'confirmLogout': 'هل أنت متأكد من تسجيل الخروج؟',
      'couldNotLoadProfile': 'تعذر تحميل الملف الشخصي',
      'ensureLoggedIn': 'يرجى التأكد من تسجيل الدخول.',

      // Connectivity banner
      'noInternetConnection': 'لا يوجد اتصال بالإنترنت. بعض الميزات قد لا تعمل.',
      'slowConnection': 'اتصال بطيء. التحميل قد يستغرق وقتاً أطول.',
      'connectionRestored': 'تم استعادة الاتصال',

      // Requirements checklist
      'academicTranscripts': 'كشف الدرجات الأكاديمية',
      'bachelorCertificate': 'شهادة البكالوريوس',
      'sopMotivationLetter': 'البيان الشخصي / رسالة التحفيز',
      'cvResume': 'السيرة الذاتية',
      'languageCertOptional': 'شهادة لغة (آيلتس/توفل) — اختياري',

      // Payment / Paywall
      'pleaseSignInFirst': 'يرجى تسجيل الدخول أولاً',
      'checkingPaymentStatus': 'جارٍ التحقق من حالة الدفع...',
      'paymentDelayed': 'تم استلام الدفع ولكن التفعيل متأخر. سيتم التفعيل قريباً.',

      // AI Generator
      'links': 'روابط',
      'failedToGeneratePdf': 'فشل إنشاء PDF: {error}',
      'fillNameAndBackground': 'يرجى إدخال اسمك وخلفيتك.',
      'copiedToClipboard': 'تم النسخ إلى الحافظة!',
      'generateCvSopAi': 'إنشاء سيرة ذاتية / بيان شخصي بالذكاء الاصطناعي',
      'copy': 'نسخ',
      'downloadPdf': 'تحميل PDF',
      'replaceFile': 'استبدال الملف',
      'cvGenerated': 'تم إنشاء السيرة الذاتية',
      'motivationLetterGenerated': 'تم إنشاء رسالة التحفيز',

      // Comparison
      'compare': 'مقارنة',
      'compareUniversities': 'مقارنة الجامعات',
      'selectUniversities': 'اختر الجامعات للمقارنة',
      'feature': 'الميزة',
      'noDeadlines': 'لا توجد مواعيد نهائية في هذا اليوم',

      // Calendar
      'deadlineCalendar': 'تقويم المواعيد',
      'upcomingDeadlinesCount': 'المواعيد القادمة',

      // Templates
      'documentTemplates': 'قوالب المستندات',
      'cvTemplate': 'السيرة الذاتية - النمط الألماني',
      'motivationLetterTemplate': 'قالب رسالة التحفيز',
      'recommendationTemplate': 'طلب خطاب توصية',

      // Dashboard
      'avgMatch': 'نسبة التطابق',
      'byStatus': 'حسب الحالة',

      // Back
      'pressAgainToExit': 'اضغط مرة أخرى للخروج',
    },
  };

  String translate(String key) {
    return _localizedStrings[locale.languageCode]?[key] ?? key;
  }

  static Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations.load(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
