import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'appTitle': 'UniPath',
      'home': 'Home',
      'search': 'Search',
      'applications': 'Applications',
      'profile': 'Profile',
      'settings': 'Settings',
      'accountSettings': 'Account Settings',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'save': 'Save',
      'edit': 'Edit',
      'cancel': 'Cancel',
      'deleteAccount': 'Delete Account',
      'deleteAccountWarning': 'Are you sure? This action cannot be undone.',
      'yesDelete': 'Yes, Delete',
      'name': 'Name',
      'email': 'Email',
      'gpa': 'GPA',
      'nationality': 'Nationality',
      'preferredCities': 'Preferred Cities',
      'budgetRange': 'Budget Range',
      'notifications': 'Notifications',
      'deadlineReminders': 'Deadline Reminders',
      'generalNotifications': 'General Notifications',
      'profileCompleteness': 'Profile Completeness',
      'matchScore': 'Your Match Score',
      'goodChance': 'Good Chance',
      'strongMatch': 'Strong Match',
      'fairMatch': 'Fair Match',
      'weakMatch': 'Weak Match',
      'notRecommended': 'Not Recommended',
      'excellentMatch': 'Excellent Match',
      'recommendedForYou': 'Recommended for you',
      'seeAll': 'See all',
      'findPrograms': 'Find Programs',
      'aiAdvisor': 'AI Advisor',
      'sopAssistant': 'SOP Assistant',
      'cvBuilder': 'CV Builder',
      'noIelts': 'No IELTS',
      'englishProgram': 'English Program',
      'tuition': 'Tuition',
      'location': 'Location',
      'intake': 'Intake',
      'degree': 'Degree',
      'major': 'Major',
      'languageOfInstruction': 'Language of Instruction',
      'ielts': 'IELTS',
      'toefl': 'TOEFL',
      'moi': 'MOI',
      'uploadDocuments': 'Upload Documents',
      'aiReview': 'AI Document Review',
      'aiTips': 'AI Improvement Tips',
      'remainingUses': 'Remaining uses:',
      'premiumFeature': 'Premium Feature',
      'premiumDescription':
          'This is a premium feature. Please upgrade your plan.',
      // 'goToPayment': 'Go to Payment', // removed - no payment screen
      'settingsSaved': 'Settings saved successfully!',
      'noDocuments': 'No documents uploaded yet',
      'checkRequirements': 'Check the Requirements tab above',
      'overBudget': 'Over Budget',
      'withinBudget': 'Within Budget',
      'preferredCity': 'Preferred City',
      'personalInfo': 'Personal Info',
      'academicProfile': 'Academic Profile',
      'preferences': 'Preferences',
      'languageCertificate': 'Language Certificate',
      'appSettings': 'App Settings',
      'fieldOfStudy': 'Field of Study',
      'degreeLevel': 'Degree Level',
      'studyLanguage': 'Study Language',
      'targetIntake': 'Target Intake',
      'gpaScale': 'GPA Scale',
      'all': 'All',
      'saved': 'Saved',
      'preparing': 'Preparing',
      'applied': 'Applied',
      'waiting': 'Waiting',
      'accepted': 'Accepted',
      'deadline': 'Deadline',
      'docs': 'Docs',
      'chance': 'Chance',
      'expired': 'Expired',
      'today': 'Today',
      'inDays': 'In %d days',
      'viewDetails': 'View Details',
      'searchPrograms': 'Search programs or universities...',
      'studyInGermany': 'Study in Germany',
      'upcomingDeadlines': 'Upcoming Deadlines',
      'yourMatchAverage': 'Your Match Average',
      'inTheNext30Days': 'In the next 30 days',
      'high': 'High',
      'medium': 'Medium',
      'requirementsChecklist': 'Requirements Checklist',
      'close': 'Close',
      'noApplicationsFound': 'No applications found',
      'programsMatch': 'Programs Match Your Profile',
      'loadingMore': 'Loading more...',
      'seenAllPrograms': "You've seen all available programs!",
      'universitiesFound': 'Universities Found',
      'retry': 'Retry',
      'searchForCourses': 'Search for courses or universities...',
      'filters': 'Filters',
      'clearAll': 'Clear All',
      'ieltsRequired': 'IELTS Required',
      'moiAccepted': 'MOI Accepted',
      'maxTuitionPerYear': 'Max Tuition / Year',
      'instructionLanguage': 'Instruction Language',
      'locationCity': 'Location / City',
      'allLocations': 'All Locations',
      'logout': 'Logout',
      'login': 'Login',
      'register': 'Register',
      'welcomeBack': 'Welcome Back!',
      'loginSubtitle': 'Login to continue your study abroad journey',
      'emailOrUsername': 'Email address or Username',
      'enterEmailOrUsername': 'Please enter your email or username',
      'enterPassword': 'Please enter your password',
      'passwordMinLength': 'Password must be at least 6 characters',
      'forgotPassword': 'Forgot password?',
      'rememberMe': 'Remember me',
      'or': 'or',
      'noAccount': "Don't have an account? ",
      'createAccount': 'Create Account',
      'registerSubtitle': 'Join UniPath to achieve your dreams in Germany.',
      'username': 'Username',
      'enterUsername': 'Please enter a username',
      'usernameMinLength': 'Username must be at least 3 characters',
      'phoneOptional': 'Phone (optional)',
      'enterEmailAddress': 'Please enter your email address',
      'enterValidEmail': 'Please enter a valid email address',
      'enterPasswordRegister': 'Please enter a password',
      'passwordMinLengthRegister': 'Password must be at least 6 characters',
      'confirmPassword': 'Confirm password',
      'confirmYourPassword': 'Please confirm your password',
      'passwordsNotMatch': 'Passwords do not match',
      'alreadyHaveAccount': 'Already have an account? ',
      'overview': 'Overview',
      'curriculum': 'Curriculum',
      'checklist': 'Checklist',
      'notes': 'Notes',
      'free': 'Free',
      'nonRefundable': 'Non-refundable',
      'freeProgram': 'Free Program',
      'perYear': 'Per Year',
      'noDeadline': 'No deadline',
      'notAvailable': 'N/A',
      'aboutUniversity': 'About the University',
      'descriptionPlaceholder': 'Detailed description about the university will be available soon.',
      'readMore': 'Read more',
      'programCurriculum': 'Program Curriculum',
      'noDetails': 'No details',
      'noCurriculumData': 'No curriculum data.',
      'filterAiRecommended': 'Filter AI Recommended tracks for your profile',
      'askUniPathAi': 'Ask UniPath AI',
      'welcomeTitle': "Let's personalize\nyour experience",
      'welcomeSubtitle':
          'We\'ll ask you a few questions to find the best universities and programs for you.',
      'intakeHeading': 'When do you want to\nstart studying?',
      'studyLevelHeading': 'What level of study are\nyou looking for?',
      'studyLevelSubtitle': 'You can select your target degree',
      'majorHeading': 'Select your major\nfield of study',
      'majorSubtitle':
          'Choose the discipline that matches your academic background',
      'langHeading': 'Your Language\nPreference',
      'langSubtitle': 'Select the language you wish to study in.',
      'ieltsHeading': 'English Language\nProficiency',
      'ieltsSubtitle': 'Which English proficiency test do you have?',
      'ieltsScoreHeading': 'What is your overall\nIELTS band score?',
      'ieltsScoreSubtitle':
          'Drag the slider to match your certificate score',
      'moiHeading': 'MOI Confirmation',
      'moiSubtitle':
          'Do you confirm that your previous education was taught entirely in English?',
      'moiConfirmYes': 'Yes, I confirm',
      'moiConfirmYesSub': 'My degree was taught completely in English',
      'moiConfirmNo': 'No, go back',
      'moiConfirmNoSub': 'Choose a different option',
      'tokenHeading': 'Authentication Token',
      'tokenSubtitle':
          'Enter your authentication token if you have one (Optional)',
      'tokenLabel': 'Token (Optional)',
      'tokenHint': 'Enter your token here...',
      'noneHeading': 'No English Certificate',
      'noneSubtitle':
          'You selected that you don\'t have any English certificate. Some programs may require one.',
      'noneNote': 'Note',
      'noneNoteBody':
          'You can still apply to programs that don\'t require English certificates or accept MOI.',
      'gpaHeading': 'Your Academic\nPerformance',
      'gpaSubtitle': 'Enter your cumulative GPA or percentage',
      'gpaScaleLabel': 'GPA Scale System',
      'gpaEarnedLabel': 'Earned GPA / Score',
      'gpaHint4': 'Enter a value between 0.0 and 4.0',
      'gpaHint5': 'Enter a value between 0.0 and 5.0',
      'gpaHint100': 'Enter your overall percentage (0 - 100)',
      'budgetHeading': 'What is your tuition\nbudget per year?',
      'budgetSubtitle': 'Select the maximum tuition fees you can afford',
      'goalsHeading': 'What are your primary\nstudy goals?',
      'goalsSubtitle': 'Select all that apply to your future plans',
      'btnGetStarted': "Let's Get Started \u2192",
      'btnLooksGood': 'Looks Good! \u2192',
      'btnContinue': 'Continue',
      'valIntake': 'Please select when you want to start studying',
      'valStudyLevel': 'Please select your study level',
      'valMajor': 'Please select your field of interest',
      'valLanguage': 'Please select your language preference',
      'valTestType': 'Please select your English proficiency test',
      'valScore': 'Please enter your test score',
      'valGpa': 'Please enter your GPA',
      'valGpaScale': 'Please select your GPA scale',
      'valMoiConfirm': 'Please confirm that you have an MOI letter',
      'valBudget': 'Please select your budget range',
      'notesSaved': 'Notes saved successfully!',
      'errorSavingNotes': 'Error saving notes',
      'monthlyLimitReached': 'Monthly limit reached (10 uses). Upgrade for unlimited!',
      // 'paymentComingSoon': 'Payment screen coming soon', // removed
      'noDocumentsUploaded': 'No documents uploaded yet. Upload your documents from the checklist above (Transcripts, CV, SOP, Certificate).',
      'profileDataNotLoaded': 'Profile data not loaded yet. Try again.',
      'comingSoon': 'Coming soon',
      'welcomeAccountCreated': 'Account created successfully! Welcome to UniPath!',
      'welcomeBackLogin': 'Welcome back! Successfully logged in.',
      'loggedOutSuccess': 'Logged out successfully!',
      'uploadDescription': 'Files uploaded here will automatically be used for all your German university applications.',
      'reviewingDocuments': 'Reviewing Your Documents',
      'starting': 'Starting...',
      'downloadLabel': 'Downloading',
      'analyzeLabel': 'Analyzing',
      'recommendationsLabel': 'Getting recommendations for',
      'cachedLabel': 'Cached',
      'downloadTimedOut': 'Download timed out. Check your internet connection.',
      'serverReturned': 'Server returned {code}. Try again later.',
      'couldNotDownload': 'Could not download the file. Check your connection.',
      'aiFailed': 'AI analysis failed: {error}',
      'uploadThisDoc': 'Upload this document to get specific feedback.',
      'reviewFailed': 'Failed to review documents. Check your connection.',
      'uploadDocumentTitle': 'Upload Document',
      'pdfFile': 'PDF File',
      'pdfSubtitle': 'Choose a PDF from your device (max 10 MB)',
      'gallery': 'Gallery',
      'gallerySubtitle': 'Pick an image from your gallery',
      'camera': 'Camera',
      'cameraSubtitle': 'Take a photo of your document',
      'fileTooLarge': 'File too large. Maximum size is 20 MB.',
      'resetPassword': 'Reset Password',
      'send': 'Send',
      'passwordResetSent': 'Password reset email sent! Check your inbox.',
    },
    'ar': {
      'appTitle': 'يوني باث',
      'home': 'الرئيسية',
      'search': 'بحث',
      'applications': 'الطلبات',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'accountSettings': 'إعدادات الحساب',
      'darkMode': 'الوضع الليلي',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'save': 'حفظ',
      'edit': 'تعديل',
      'cancel': 'إلغاء',
      'deleteAccount': 'حذف الحساب',
      'deleteAccountWarning':
          'هل أنت متأكد؟ لا يمكن التراجع عن هذا الإجراء.',
      'yesDelete': 'نعم، احذف',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'gpa': 'المعدل',
      'nationality': 'الجنسية',
      'preferredCities': 'المدن المفضلة',
      'budgetRange': 'نطاق الميزانية',
      'notifications': 'الإشعارات',
      'deadlineReminders': 'تذكيرات المواعيد',
      'generalNotifications': 'الإشعارات العامة',
      'profileCompleteness': 'اكتمال الملف',
      'matchScore': 'نسبة التطابق',
      'goodChance': 'فرصة جيدة',
      'strongMatch': 'تطابق قوي',
      'fairMatch': 'تطابق متوسط',
      'weakMatch': 'تطابق ضعيف',
      'notRecommended': 'غير موصى به',
      'excellentMatch': 'تطابق ممتاز',
      'recommendedForYou': 'موصى به لك',
      'seeAll': 'عرض الكل',
      'findPrograms': 'البحث عن برامج',
      'aiAdvisor': 'المستشار الذكي',
      'sopAssistant': 'مساعد البيان الشخصي',
      'cvBuilder': 'بناء السيرة الذاتية',
      'noIelts': 'بدون آيلتس',
      'englishProgram': 'برنامج إنجليزي',
      'tuition': 'الرسوم',
      'location': 'الموقع',
      'intake': 'موعد التقديم',
      'degree': 'الدرجة العلمية',
      'major': 'التخصص',
      'languageOfInstruction': 'لغة التدريس',
      'ielts': 'آيلتس',
      'toefl': 'توفل',
      'moi': 'شهادة اللغة',
      'uploadDocuments': 'رفع المستندات',
      'aiReview': 'مراجعة المستندات بالذكاء الاصطناعي',
      'aiTips': 'نصائح التحسين بالذكاء الاصطناعي',
      'remainingUses': 'الاستخدامات المتبقية:',
      'premiumFeature': 'ميزة مدفوعة',
      'premiumDescription': 'هذه ميزة مدفوعة. يرجى ترقية باقتك.',
      // 'goToPayment': 'اذهب للدفع', // removed - no payment screen
      'settingsSaved': 'تم حفظ الإعدادات بنجاح!',
      'noDocuments': 'لم يتم رفع أي مستندات بعد',
      'checkRequirements': 'تفقد قسم المتطلبات أعلاه',
      'overBudget': 'فوق الميزانية',
      'withinBudget': 'ضمن الميزانية',
      'preferredCity': 'المدينة المفضلة',
      'personalInfo': 'المعلومات الشخصية',
      'academicProfile': 'الملف الأكاديمي',
      'preferences': 'التفضيلات',
      'languageCertificate': 'شهادة اللغة',
      'appSettings': 'إعدادات التطبيق',
      'fieldOfStudy': 'مجال الدراسة',
      'degreeLevel': 'المستوى الدراسي',
      'studyLanguage': 'لغة الدراسة',
      'targetIntake': 'موعد التقديم',
      'gpaScale': 'مقياس المعدل',
      'all': 'الكل',
      'saved': 'محفوظ',
      'preparing': 'قيد التحضير',
      'applied': 'مقدم',
      'waiting': 'قيد الانتظار',
      'accepted': 'مقبول',
      'deadline': 'آخر موعد',
      'docs': 'المستندات',
      'chance': 'الفرصة',
      'expired': 'منتهي',
      'today': 'اليوم',
      'inDays': 'بعد %d أيام',
      'viewDetails': 'عرض التفاصيل',
      'searchPrograms': 'ابحث عن برامج أو جامعات...',
      'studyInGermany': 'ادرس في ألمانيا',
      'upcomingDeadlines': 'المواعيد القادمة',
      'yourMatchAverage': 'متوسط التطابق',
      'inTheNext30Days': 'في الـ 30 يوماً القادمة',
      'high': 'عالية',
      'medium': 'متوسطة',
      'requirementsChecklist': 'قائمة المتطلبات',
      'close': 'إغلاق',
      'noApplicationsFound': 'لا توجد طلبات',
      'programsMatch': 'برنامج تطابق ملفك',
      'loadingMore': 'جارٍ التحميل...',
      'seenAllPrograms': 'لقد رأيت جميع البرامج المتاحة!',
      'universitiesFound': 'جامعة موجودة',
      'retry': 'إعادة المحاولة',
      'searchForCourses': 'ابحث عن courses أو جامعات...',
      'filters': 'تصفية',
      'clearAll': 'مسح الكل',
      'ieltsRequired': 'مطلوب آيلتس',
      'moiAccepted': 'مقبول شهادة لغة',
      'maxTuitionPerYear': 'الحد الأقصى للرسوم / سنة',
      'instructionLanguage': 'لغة التدريس',
      'locationCity': 'الموقع / المدينة',
      'allLocations': 'جميع المواقع',
      'logout': 'تسجيل الخروج',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'welcomeBack': 'مرحباً بعودتك!',
      'loginSubtitle': 'سجل الدخول لمواصلة رحلة دراستك في الخارج',
      'emailOrUsername': 'البريد الإلكتروني أو اسم المستخدم',
      'enterEmailOrUsername': 'الرجاء إدخال البريد الإلكتروني أو اسم المستخدم',
      'enterPassword': 'الرجاء إدخال كلمة المرور',
      'passwordMinLength': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'rememberMe': 'تذكرني',
      'or': 'أو',
      'noAccount': 'ليس لديك حساب؟ ',
      'createAccount': 'إنشاء حساب',
      'registerSubtitle': 'انضم إلى يوني باث لتحقيق أحلامك في ألمانيا.',
      'username': 'اسم المستخدم',
      'enterUsername': 'الرجاء إدخال اسم المستخدم',
      'usernameMinLength': 'يجب أن يكون اسم المستخدم 3 أحرف على الأقل',
      'phoneOptional': 'الهاتف (اختياري)',
      'enterEmailAddress': 'الرجاء إدخال عنوان البريد الإلكتروني',
      'enterValidEmail': 'الرجاء إدخال بريد إلكتروني صحيح',
      'enterPasswordRegister': 'الرجاء إدخال كلمة المرور',
      'passwordMinLengthRegister': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'confirmPassword': 'تأكيد كلمة المرور',
      'confirmYourPassword': 'الرجاء تأكيد كلمة المرور',
      'passwordsNotMatch': 'كلمة المرور غير متطابقة',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟ ',
      'overview': 'نظرة عامة',
      'curriculum': 'المنهج',
      'checklist': 'قائمة المتطلبات',
      'notes': 'ملاحظات',
      'free': 'مجاني',
      'nonRefundable': 'غير قابل للاسترداد',
      'freeProgram': 'برنامج مجاني',
      'perYear': 'في السنة',
      'noDeadline': 'لا يوجد موعد',
      'notAvailable': 'غير متاح',
      'aboutUniversity': 'عن الجامعة',
      'descriptionPlaceholder': 'الوصف التفصيلي عن الجامعة سيكون متاحاً قريباً.',
      'readMore': 'اقرأ المزيد',
      'programCurriculum': 'المنهج الدراسي',
      'noDetails': 'لا توجد تفاصيل',
      'noCurriculumData': 'لا توجد بيانات منهج.',
      'filterAiRecommended': 'تصفية المسارات الموصى بها بالذكاء الاصطناعي لملفك',
      'askUniPathAi': 'اسأل يوني باث',
      'welcomeTitle': 'دعنا نخصص\nتجربتك',
      'welcomeSubtitle':
          'سنطرح عليك بعض الأسئلة للعثور على أفضل الجامعات والبرامج المناسبة لك.',
      'intakeHeading': 'متى تريد أن\nتبدأ الدراسة؟',
      'studyLevelHeading': 'ما المستوى الدراسي\nالذي تبحث عنه؟',
      'studyLevelSubtitle': 'يمكنك اختيار الدرجة المستهدفة',
      'majorHeading': 'اختر تخصصك\nالدراسي',
      'majorSubtitle': 'اختر المجال الذي يتناسب مع خلفيتك الأكاديمية',
      'langHeading': 'تفضيل\nاللغة',
      'langSubtitle': 'اختر اللغة التي ترغب في الدراسة بها.',
      'ieltsHeading': 'اختبار اللغة\nالإنجليزية',
      'ieltsSubtitle': 'ما هو اختبار اللغة الإنجليزية الذي لديك؟',
      'ieltsScoreHeading': 'ما هي درجة\nالآيلتس الإجمالية لديك؟',
      'ieltsScoreSubtitle': 'اسحب الشريط لمطابقة درجة شهادتك',
      'moiHeading': 'تأكيد شهادة اللغة',
      'moiSubtitle':
          'هل تؤكد أن تعليمك السابق كان باللغة الإنجليزية بالكامل؟',
      'moiConfirmYes': 'نعم، أؤكد',
      'moiConfirmYesSub': 'دراستي كانت باللغة الإنجليزية بالكامل',
      'moiConfirmNo': 'لا، عد للخلف',
      'moiConfirmNoSub': 'اختيار خيار آخر',
      'tokenHeading': 'رمز التوثيق',
      'tokenSubtitle': 'أدخل رمز التوثيق إذا كان لديك (اختياري)',
      'tokenLabel': 'الرمز (اختياري)',
      'tokenHint': 'أدخل الرمز هنا...',
      'noneHeading': 'لا توجد شهادة لغة',
      'noneSubtitle':
          'لقد اخترت أنه ليس لديك شهادة لغة إنجليزية. بعض البرامج قد تتطلب واحدة.',
      'noneNote': 'ملاحظة',
      'noneNoteBody':
          'لا يزال بإمكانك التقدم للبرامج التي لا تتطلب شهادات لغة إنجليزية أو تقبل MOI.',
      'gpaHeading': 'أدائك\nالأكاديمي',
      'gpaSubtitle': 'أدخل معدلك التراكمي أو النسبة المئوية',
      'gpaScaleLabel': 'نظام مقياس المعدل',
      'gpaEarnedLabel': 'المعدل / الدرجة',
      'gpaHint4': 'أدخل قيمة بين 0.0 و 4.0',
      'gpaHint5': 'أدخل قيمة بين 0.0 و 5.0',
      'gpaHint100': 'أدخل النسبة المئوية الإجمالية (0 - 100)',
      'budgetHeading': 'ما هي ميزانية\nالرسوم الدراسية سنوياً؟',
      'budgetSubtitle': 'اختر الحد الأقصى للرسوم الذي يمكنك تحمله',
      'goalsHeading': 'ما هي أهدافك\nالدراسية الأساسية؟',
      'goalsSubtitle': 'اختر كل ما ينطبق على خططك المستقبلية',
      'btnGetStarted': 'لنبدأ \u2192',
      'btnLooksGood': 'يبدو جيداً! \u2192',
      'btnContinue': 'متابعة',
      'valIntake': 'الرجاء اختيار موعد بدء الدراسة',
      'valStudyLevel': 'الرجاء اختيار المستوى الدراسي',
      'valMajor': 'الرجاء اختيار مجال الاهتمام',
      'valLanguage': 'الرجاء اختيار تفضيل اللغة',
      'valTestType': 'الرجاء اختيار اختبار اللغة الإنجليزية',
      'valScore': 'الرجاء إدخال درجة الاختبار',
      'valGpa': 'الرجاء إدخال المعدل',
      'valGpaScale': 'الرجاء اختيار مقياس المعدل',
      'valMoiConfirm': 'الرجاء تأكيد أن لديك خطاب MOI',
      'valBudget': 'الرجاء اختيار نطاق الميزانية',
      'notesSaved': 'تم حفظ الملاحظات بنجاح!',
      'errorSavingNotes': 'خطأ في حفظ الملاحظات',
      'monthlyLimitReached': 'لقد وصلت للحد الشهري (10 استخدامات). قم بالترقية للاستخدام غير المحدود!',
      // 'paymentComingSoon': 'شاشة الدفع قريباً', // removed
      'noDocumentsUploaded': 'لم يتم رفع أي مستندات بعد. قم برفع مستنداتك من قائمة المتطلبات أعلاه (كشف الدرجات، السيرة الذاتية، بيان الغرض، الشهادة).',
      'profileDataNotLoaded': 'بيانات الملف الشخصي لم يتم تحميلها بعد. حاول مرة أخرى.',
      'comingSoon': 'قريباً',
      'welcomeAccountCreated': 'تم إنشاء الحساب بنجاح! مرحباً بك في يوني باث!',
      'welcomeBackLogin': 'مرحباً بعودتك! تم تسجيل الدخول بنجاح.',
      'loggedOutSuccess': 'تم تسجيل الخروج بنجاح!',
      'uploadDescription': 'الملفات التي يتم رفعها هنا ستُستخدم تلقائياً في جميع طلبات التقديم للجامعات الألمانية.',
      'reviewingDocuments': 'مراجعة مستنداتك',
      'starting': 'جارٍ البدء...',
      'downloadLabel': 'جارٍ التحميل',
      'analyzeLabel': 'جارٍ التحليل',
      'recommendationsLabel': 'جارٍ الحصول على التوصيات لـ',
      'cachedLabel': 'مخبأ',
      'downloadTimedOut': 'انتهت مهلة التحميل. تحقق من اتصالك بالإنترنت.',
      'serverReturned': 'الخادم أرجع {code}. حاول مرة أخرى لاحقاً.',
      'couldNotDownload': 'تعذر تحميل الملف. تحقق من اتصالك.',
      'aiFailed': 'فشل تحليل الذكاء الاصطناعي: {error}',
      'uploadThisDoc': 'قم برفع هذا المستند للحصول على تقييم محدد.',
      'reviewFailed': 'فشلت مراجعة المستندات. تحقق من اتصالك.',
      'uploadDocumentTitle': 'رفع مستند',
      'pdfFile': 'ملف PDF',
      'pdfSubtitle': 'اختر PDF من جهازك (الحد الأقصى 10 ميجابايت)',
      'gallery': 'المعرض',
      'gallerySubtitle': 'اختر صورة من معرض الصور',
      'camera': 'الكاميرا',
      'cameraSubtitle': 'التقط صورة للمستند',
      'fileTooLarge': 'الملف كبير جداً. الحد الأقصى 20 ميجابايت.',
      'resetPassword': 'إعادة تعيين كلمة المرور',
      'send': 'إرسال',
      'passwordResetSent': 'تم إرسال بريد إعادة تعيين كلمة المرور! تحقق من بريدك الوارد.',
    },
  };

  String translate(String key) {
    return _localizedStrings[locale.languageCode]?[key] ?? key;
  }

  static Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations.load(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
