import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'appTitle': 'UniPath',
      'home': 'Home',
      'search': 'Search',
      'applications': 'Applications',
      'profile': 'Profile',
      'settings': 'Settings',
      'accountSettings': 'Account Settings',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'save': 'Save',
      'edit': 'Edit',
      'cancel': 'Cancel',
      'deleteAccount': 'Delete Account',
      'deleteAccountWarning': 'Are you sure? This action cannot be undone.',
      'yesDelete': 'Yes, Delete',
      'name': 'Name',
      'email': 'Email',
      'gpa': 'GPA',
      'nationality': 'Nationality',
      'preferredCities': 'Preferred Cities',
      'budgetRange': 'Budget Range',
      'notifications': 'Notifications',
      'deadlineReminders': 'Deadline Reminders',
      'generalNotifications': 'General Notifications',
      'profileCompleteness': 'Profile Completeness',
      'matchScore': 'Your Match Score',
      'goodChance': 'Good Chance',
      'strongMatch': 'Strong Match',
      'fairMatch': 'Fair Match',
      'weakMatch': 'Weak Match',
      'notRecommended': 'Not Recommended',
      'excellentMatch': 'Excellent Match',
      'recommendedForYou': 'Recommended for you',
      'seeAll': 'See all',
      'findPrograms': 'Find Programs',
      'aiAdvisor': 'AI Advisor',
      'sopAssistant': 'SOP Assistant',
      'cvBuilder': 'CV Builder',
      'noIelts': 'No IELTS',
      'englishProgram': 'English Program',
      'tuition': 'Tuition',
      'location': 'Location',
      'intake': 'Intake',
      'degree': 'Degree',
      'major': 'Major',
      'languageOfInstruction': 'Language of Instruction',
      'ielts': 'IELTS',
      'toefl': 'TOEFL',
      'moi': 'MOI',
      'uploadDocuments': 'Upload Documents',
      'aiReview': 'AI Document Review',
      'aiTips': 'AI Improvement Tips',
      'remainingUses': 'Remaining uses:',
      'premiumFeature': 'Premium Feature',
      'premiumDescription':
          'This is a premium feature. Please upgrade your plan.',
      // 'goToPayment': 'Go to Payment', // removed - no payment screen
      'settingsSaved': 'Settings saved successfully!',
      'noDocuments': 'No documents uploaded yet',
      'checkRequirements': 'Check the Requirements tab above',
      'overBudget': 'Over Budget',
      'withinBudget': 'Within Budget',
      'preferredCity': 'Preferred City',
      'personalInfo': 'Personal Info',
      'academicProfile': 'Academic Profile',
      'preferences': 'Preferences',
      'languageCertificate': 'Language Certificate',
      'appSettings': 'App Settings',
      'fieldOfStudy': 'Field of Study',
      'degreeLevel': 'Degree Level',
      'studyLanguage': 'Study Language',
      'targetIntake': 'Target Intake',
      'gpaScale': 'GPA Scale',
      'all': 'All',
      'saved': 'Saved',
      'preparing': 'Preparing',
      'applied': 'Applied',
      'waiting': 'Waiting',
      'accepted': 'Accepted',
      'deadline': 'Deadline',
      'docs': 'Docs',
      'chance': 'Chance',
      'expired': 'Expired',
      'today': 'Today',
      'inDays': 'In %d days',
      'viewDetails': 'View Details',
      'searchPrograms': 'Search programs or universities...',
      'studyInGermany': 'Study in Germany',
      'upcomingDeadlines': 'Upcoming Deadlines',
      'yourMatchAverage': 'Your Match Average',
      'inTheNext30Days': 'In the next 30 days',
      'high': 'High',
      'medium': 'Medium',
      'requirementsChecklist': 'Requirements Checklist',
      'close': 'Close',
      'noApplicationsFound': 'No applications found',
      'programsMatch': 'Programs Match Your Profile',
      'loadingMore': 'Loading more...',
      'seenAllPrograms': "You've seen all available programs!",
      'universitiesFound': 'Universities Found',
      'retry': 'Retry',
      'searchForCourses': 'Search for courses or universities...',
      'filters': 'Filters',
      'clearAll': 'Clear All',
      'ieltsRequired': 'IELTS Required',
      'moiAccepted': 'MOI Accepted',
      'maxTuitionPerYear': 'Max Tuition / Year',
      'instructionLanguage': 'Instruction Language',
      'locationCity': 'Location / City',
      'allLocations': 'All Locations',
      'logout': 'Logout',
      'login': 'Login',
      'register': 'Register',
      'welcomeBack': 'Welcome Back!',
      'loginSubtitle': 'Login to continue your study abroad journey',
      'emailOrUsername': 'Email address or Username',
      'enterEmailOrUsername': 'Please enter your email or username',
      'enterPassword': 'Please enter your password',
      'passwordMinLength': 'Password must be at least 6 characters',
      'forgotPassword': 'Forgot password?',
      'rememberMe': 'Remember me',
      'or': 'or',
      'noAccount': "Don't have an account? ",
      'createAccount': 'Create Account',
      'registerSubtitle': 'Join UniPath to achieve your dreams in Germany.',
      'username': 'Username',
      'enterUsername': 'Please enter a username',
      'usernameMinLength': 'Username must be at least 3 characters',
      'phoneOptional': 'Phone (optional)',
      'enterEmailAddress': 'Please enter your email address',
      'enterValidEmail': 'Please enter a valid email address',
      'enterPasswordRegister': 'Please enter a password',
      'passwordMinLengthRegister': 'Password must be at least 6 characters',
      'confirmPassword': 'Confirm password',
      'confirmYourPassword': 'Please confirm your password',
      'passwordsNotMatch': 'Passwords do not match',
      'alreadyHaveAccount': 'Already have an account? ',
      'overview': 'Overview',
      'curriculum': 'Curriculum',
      'checklist': 'Checklist',
      'notes': 'Notes',
      'free': 'Free',
      'nonRefundable': 'Non-refundable',
      'freeProgram': 'Free Program',
      'perYear': 'Per Year',
      'noDeadline': 'No deadline',
      'notAvailable': 'N/A',
      'descriptionPlaceholder': 'Detailed description about the university will be available soon.',
      'readMore': 'Read more',
      'programCurriculum': 'Program Curriculum',
      'noDetails': 'No details',
      'noCurriculumData': 'No curriculum data.',
      'filterAiRecommended': 'Filter AI Recommended tracks for your profile',
      'askUniPathAi': 'Ask UniPath AI',
      'welcomeTitle': "Let's personalize\nyour experience",
      'welcomeSubtitle':
          'We\'ll ask you a few questions to find the best universities and programs for you.',
      'intakeHeading': 'When do you want to\nstart studying?',
      'studyLevelHeading': 'What level of study are\nyou looking for?',
      'studyLevelSubtitle': 'You can select your target degree',
      'majorHeading': 'Select your major\nfield of study',
      'majorSubtitle':
          'Choose the discipline that matches your academic background',
      'langHeading': 'Your Language\nPreference',
      'langSubtitle': 'Select the language you wish to study in.',
      'ieltsHeading': 'English Language\nProficiency',
      'ieltsSubtitle': 'Which English proficiency test do you have?',
      'ieltsScoreHeading': 'What is your overall\nIELTS band score?',
      'ieltsScoreSubtitle':
          'Drag the slider to match your certificate score',
      'moiHeading': 'MOI Confirmation',
      'moiSubtitle':
          'Do you confirm that your previous education was taught entirely in English?',
      'moiConfirmYes': 'Yes, I confirm',
      'moiConfirmYesSub': 'My degree was taught completely in English',
      'moiConfirmNo': 'No, go back',
      'moiConfirmNoSub': 'Choose a different option',
      'tokenHeading': 'Authentication Token',
      'tokenSubtitle':
          'Enter your authentication token if you have one (Optional)',
      'tokenLabel': 'Token (Optional)',
      'tokenHint': 'Enter your token here...',
      'noneHeading': 'No English Certificate',
      'noneSubtitle':
          'You selected that you don\'t have any English certificate. Some programs may require one.',
      'noneNote': 'Note',
      'noneNoteBody':
          'You can still apply to programs that don\'t require English certificates or accept MOI.',
      'gpaHeading': 'Your Academic\nPerformance',
      'gpaSubtitle': 'Enter your cumulative GPA or percentage',
      'gpaScaleLabel': 'GPA Scale System',
      'gpaEarnedLabel': 'Earned GPA / Score',
      'gpaHint4': 'Enter a value between 0.0 and 4.0',
      'gpaHint5': 'Enter a value between 0.0 and 5.0',
      'gpaHint100': 'Enter your overall percentage (0 - 100)',
      'budgetHeading': 'What is your tuition\nbudget per year?',
      'budgetSubtitle': 'Select the maximum tuition fees you can afford',
      'goalsHeading': 'What are your primary\nstudy goals?',
      'goalsSubtitle': 'Select all that apply to your future plans',
      'btnGetStarted': "Let's Get Started \u2192",
      'btnLooksGood': 'Looks Good! \u2192',
      'btnContinue': 'Continue',
      'valIntake': 'Please select when you want to start studying',
      'valStudyLevel': 'Please select your study level',
      'valMajor': 'Please select your field of interest',
      'valLanguage': 'Please select your language preference',
      'valTestType': 'Please select your English proficiency test',
      'valScore': 'Please enter your test score',
      'valGpa': 'Please enter your GPA',
      'valGpaScale': 'Please select your GPA scale',
      'valMoiConfirm': 'Please confirm that you have an MOI letter',
      'valBudget': 'Please select your budget range',
      'notesSaved': 'Notes saved successfully!',
      'errorSavingNotes': 'Error saving notes',
      'monthlyLimitReached': 'Monthly limit reached (10 uses). Upgrade for unlimited!',
      // 'paymentComingSoon': 'Payment screen coming soon', // removed
      'noDocumentsUploaded': 'No documents uploaded yet. Upload your documents from the checklist above (Transcripts, CV, SOP, Certificate).',
      'profileDataNotLoaded': 'Profile data not loaded yet. Try again.',
      'comingSoon': 'Coming soon',
      'welcomeAccountCreated': 'Account created successfully! Welcome to UniPath!',
      'welcomeBackLogin': 'Welcome back! Successfully logged in.',
      'loggedOutSuccess': 'Logged out successfully!',
      'uploadDescription': 'Files uploaded here will automatically be used for all your German university applications.',
      'starting': 'Starting...',
      'downloadLabel': 'Downloading',
      'analyzeLabel': 'Analyzing',
      'recommendationsLabel': 'Getting recommendations for',
      'cachedLabel': 'Cached',
      'downloadTimedOut': 'Download timed out. Check your internet connection.',
      'serverReturned': 'Server returned {code}. Try again later.',
      'couldNotDownload': 'Could not download the file. Check your connection.',
      'aiFailed': 'AI analysis failed: {error}',
      'uploadThisDoc': 'Upload this document to get specific feedback.',
      'reviewFailed': 'Failed to review documents. Check your connection.',
      'uploadDocumentTitle': 'Upload Document',
      'pdfFile': 'PDF File',
      'pdfSubtitle': 'Choose a PDF from your device (max 10 MB)',
      'gallery': 'Gallery',
      'gallerySubtitle': 'Pick an image from your gallery',
      'camera': 'Camera',
      'cameraSubtitle': 'Take a photo of your document',
      'fileTooLarge': 'File too large. Maximum size is 20 MB.',
      'resetPassword': 'Reset Password',
      'send': 'Send',
      'passwordResetSent': 'Password reset email sent! Check your inbox.',
      'loginSuccess': 'Welcome back!',
      'registerSuccess': 'Account created successfully!',
      'premium': 'Premium',
      'unlockPremium': 'Unlock Premium',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'lifetime': 'Lifetime',
      'bestValue': 'Best Value',
      'restorePurchases': 'Restore Purchases',
      'payment': 'Payment',
      'premiumActivated': 'Premium activated successfully!',
      'paymentComingSoon': 'Payment integration coming soon!',
      'perMonthShort': '/month',
      'perYearShort': '/year',
      'oneTime': 'One-time',
      'savePercent': 'Save {percent}%',
      'premiumFeatures': 'Premium Features',
      'aiReviewUnlimited': 'AI Document Review (Unlimited)',
      'aiImprovement': 'AI Improvement Suggestions',
      'premiumMatchScore': 'Premium Match Score (20%)',
      'prioritySupport': 'Priority Support',
      'unlimitedAiUses': 'Unlimited AI Uses',
      'goPremium': 'Go Premium',
      'youArePremium': 'You are Premium!',
      'premiumUntil': 'Premium until {date}',
      'unlocked': 'Unlocked',

      // Home AI Tips
      'strongProfile': 'Strong Profile',
      'strongProfileDesc': 'Your profile is a great match! Focus on submitting strong documents (CV, SOP, transcripts) for each application.',
      'polishDocuments': 'Polish Your Documents',
      'polishDocumentsDesc': 'Use the AI Document Generator on each program page to create tailored CVs and motivation letters that highlight your strengths.',
      'trackDeadlines': 'Track Deadlines',
      'trackDeadlinesDesc': 'Enable deadline reminders in Settings to never miss an application window.',
      'boostGpa': 'Boost Your GPA Score',
      'boostGpaDesc': 'Consider retaking courses or highlighting relevant project experience in your SOP to compensate.',
      'languageCert': 'Language Certificate',
      'languageCertDesc': 'Improving your IELTS score or getting an MOI certificate can add significant points to your match score.',
      'refineMajor': 'Refine Your Major',
      'refineMajorDesc': 'Visit Settings to ensure your target major is as specific as possible for better program matching.',
      'completeProfile': 'Complete Your Profile',
      'completeProfileDesc': 'Your profile is incomplete. Adding your GPA, IELTS score, and target major will dramatically improve matching.',
      'getLanguageCertified': 'Get Language Certified',
      'getLanguageCertifiedDesc': 'Most programs require IELTS (6.0+) or MOI. Adding either unlocks 10-15 points in the match score.',
      'pickIntake': 'Pick an Intake',
      'pickIntakeDesc': 'Setting your target intake helps match with programs that align with your timeline.',
      'profileNeeded': 'Profile Needed',
      'profileNeededDesc': 'Set up your academic profile in Settings — GPA, major, degree level, and language preferences.',
      'explorePrograms': 'Explore Programs',
      'exploreProgramsDesc': 'Use the Search tab to find programs. Save interesting ones to see your match score.',
      'visitSettings': 'Visit Settings',
      'visitSettingsDesc': 'Complete all profile fields to unlock personalized AI suggestions for each program.',

      // Profile screen
      'accountAndTools': 'Account & Tools',
      'myDocuments': 'My Documents',
      'cvSopCertificates': 'CV, SOP & Certificates',
      'emailTracking': 'Email Tracking',
      'emailTrackingDesc': 'Auto-detect application status from emails',
      'updateProfilePrefs': 'Update your Profile & Preferences',
      'adminDashboard': 'Admin Dashboard',
      'adminDashboardDesc': 'Manage users, universities & more',
      'signOutOfUnipath': 'Sign out of UniPath',
      'confirmLogout': 'Are you sure you want to log out?',
      'couldNotLoadProfile': 'Could not load profile',
      'ensureLoggedIn': 'Please make sure you are logged in.',

      // Connectivity banner
      'noInternetConnection': 'No internet connection. Some features may not work.',
      'slowConnection': 'Slow connection. Loading may take longer.',
      'connectionRestored': 'Connection restored',

      // Requirements checklist
      'academicTranscripts': 'Academic Transcripts',
      'bachelorCertificate': 'Bachelor Certificate',
      'sopMotivationLetter': 'SOP / Motivation Letter',
      'cvResume': 'CV / Resume',
      'languageCertOptional': 'Language Certificate (IELTS/TOEFL) — Optional',
      'germanCert': 'German Language Certificate (TestDaF, Goethe, DSH) — Optional',

      // Payment / Paywall
      'pleaseSignInFirst': 'Please sign in first',
      'checkingPaymentStatus': 'Checking payment status...',
      'paymentDelayed': 'Payment received but activation is delayed. It will activate shortly.',

      // AI Generator
      'links': 'Links',
      'failedToGeneratePdf': 'Failed to generate PDF: {error}',
      'fillNameAndBackground': 'Please fill in your name and background.',
      'copiedToClipboard': 'Copied to clipboard!',
      'generateCvSopAi': 'Generate CV / SOP with AI',
      'copy': 'Copy',
      'downloadPdf': 'Download PDF',
      'replaceFile': 'Replace file',
      'cvGenerated': 'CV Generated',
      'motivationLetterGenerated': 'Motivation Letter Generated',

      // Comparison
      'compare': 'Compare',
      'compareUniversities': 'Compare Universities',
      'selectUniversities': 'Select universities to compare',
      'feature': 'Feature',
      'noDeadlines': 'No deadlines on this day',

      // Calendar
      'deadlineCalendar': 'Deadline Calendar',
      'upcomingDeadlinesCount': 'Upcoming Deadlines',

      // Templates
      'documentTemplates': 'Document Templates',
      'cvTemplate': 'CV / Resume - German Style',
      'motivationLetterTemplate': 'Motivation Letter Template',
      'recommendationTemplate': 'Recommendation Letter Request',

      // Dashboard
      'avgMatch': 'Average Match',
      'byStatus': 'Applications by Status',

      // Back
      'pressAgainToExit': 'Press again to exit',

      // Cost of Living
      'costOfLiving': 'Cost of Living',
      'costOfLivingSubtitle': 'Estimate monthly expenses by city',
      'costOfLivingEstimator': 'Cost of Living Estimator',
      'selectCity': 'Select City',
      'monthlyLivingExpenses': 'Monthly living expenses',
      'rent': 'Rent',
      'food': 'Food',
      'insurance': 'Insurance',
      'transport': 'Transport',
      'miscellaneous': 'Miscellaneous',
      'costBreakdown': 'Cost Breakdown',
      'vsBlockedAccount': 'vs Blocked Account',
      'blockedAccount': 'Blocked Account',
      'blockedAccountInfoTitle': 'What is a Blocked Account?',
      'blockedAccountInfoBody': 'A blocked account (Sperrkonto) is required for your student visa. You need to deposit ',
      'estMonthlyCosts': 'Est. Monthly Costs',
      'remaining': 'Remaining',
      'blockedAccountTitle': 'Blocked Account 2025/26',
      'blockedAccountDesc': 'The German government requires €{yearly}/year (€{monthly}/month) in a blocked account (Sperrkonto) for your student visa. Costs vary by city — adjust your budget accordingly.',
      'overBlockedAccount': 'over blocked account',
      'remainingAfterExpenses': 'remaining after expenses',

      // Side nav
      'legal': 'Legal',
      'dangerZone': 'Danger Zone',
      'loading': 'Loading...',

      // Settings screen additional
      'privacyPolicy': 'Privacy Policy',
      'termsOfService': 'Terms of Service',
      'saving': 'Saving...',
      'saveChanges': 'Save Changes',
      'accountDeletedSuccess': 'Account deleted successfully.',
      'failedToDeleteAccount': 'Failed to delete account: ',
      'profileComplete': 'Profile complete!',
      'completeProfileForBetterMatches': 'Complete your profile to get better matches',
      'scale': 'Scale',
      'of': 'of',
      'haveYouStudiedUniversity': 'Have you studied at a university before?',
      'academicAverage': 'Academic Average (your current university average)',
      'highSchoolScore': 'High School Score (e.g. Tawjihi / Thanawiya)',
      'iHaveIelts': 'I have an IELTS certificate',
      'enterScoreBelow': 'Enter your score below',
      'someProgramsRequireIt': 'Some programs require it',
      'ieltsScoreEg': 'IELTS Score (e.g. 6.5)',
      'iHaveToefl': 'I have a TOEFL certificate',
      'acceptedByManyUniversities': 'Accepted by many German universities',
      'toeflScoreEg': 'TOEFL Score (e.g. 90)',
      'moiConfirmToggle': 'Medium of Instruction (MOI)',
      'confirmedDegreeEnglish': 'Confirmed — degree taught in English',
      'confirmIfDegreeEnglish': 'Confirm if your degree was taught in English',
      'enableNotifications': 'Enable Notifications',
      'receiveAllNotifications': 'Receive all types of notifications',
      'getRemindedBeforeDeadlines': 'Get reminded before application deadlines',
      'applicationUpdates': 'Application Updates',
      'statusChanges': 'Status changes (saved → applied → accepted/rejected)',
      'tipsNewProgramsAnnouncements': 'Tips, new programs, and announcements',
      'xSelected': '{count} selected',
      'remindMeBeforeDeadline': 'Remind me before deadline',
      'day': 'day',
      'days': 'days',
      'quietHours': 'Quiet Hours',
      'start': 'Start',
      'end': 'End',
      'select': 'Select',

      // Document Templates
      'cvGermanStyle': 'CV / Resume - German Style',
      'cvTemplateSubtitle': 'Tabular format preferred by German universities',
      'cvSectionPersonal': 'Personal Information (Name, Address, Phone, Email)',
      'cvSectionEducation': 'Education (reverse chronological order)',
      'cvSectionWork': 'Work Experience (if any)',
      'cvSectionSkills': 'Skills & Languages',
      'cvSectionInterests': 'Interests & Activities',
      'cvSectionReferences': 'References (optional)',
      'cvTip': 'Keep it concise — max 2 pages. Use Europass format or tabular CV.',
      'motivationLetterSubtitle': 'Academic-focused letter for German universities',
      'mlSectionHeader': 'Header: Your contact + University address + Date',
      'mlSectionSubject': 'Subject: "Motivation Letter for [Program Name]"',
      'mlSectionPara1': 'Paragraph 1: Introduce yourself + what you are applying for',
      'mlSectionPara2': 'Paragraph 2: Why this program? Connect your background to the program',
      'mlSectionPara3': 'Paragraph 3: Why Germany? Show knowledge of the education system',
      'mlSectionPara4': 'Paragraph 4: Your future goals — how this degree fits your career plans',
      'mlSectionClosing': 'Closing: Confident closing + signature',
      'mlTip': 'Be specific about the university and program. Generic letters are easily spotted.',
      'recommendationSubtitle': 'Professional email to ask professors for recommendation',
      'recSectionSubject': 'Subject: "Recommendation Letter Request — [Your Name]"',
      'recSectionGreeting': 'Greeting: Dear Professor [Name],',
      'recSectionIntro': 'Introduction: Remind them who you are (course, semester)',
      'recSectionRequest': 'Request: Politely ask if they would write a recommendation',
      'recSectionDetails': 'Details: Attach your CV, grades, and program list',
      'recSectionDeadline': 'Deadline: Mention when you need it',
      'recSectionClosing': 'Closing: Thank them + offer to meet in person',
      'recTip': 'Ask at least 4 weeks before the deadline. Provide all materials upfront.',
      'proTip': 'Pro Tip',
      'aiGeneratorPrompt': 'Use our AI Document Generator to create a personalized CV or Motivation Letter based on your profile. Go to any university detail page and tap "Generate CV" or "Generate Motivation Letter".',

      // Smart Document Hub
      'smartDocumentHub': 'Smart Document Hub',
      'reviewing': 'Reviewing...',
      'aiReviewAll': 'AI Review All',
      'documentReadiness': 'Document Readiness',
      'acrossSavedUniversities': 'Across {count} saved universit{plural}',
      'noSavedUniversities': 'No saved universities yet',
      'saveUniversitiesFirst': 'Save universities to your pipeline first',
      'documentsShowRequirements': 'Documents will show program-specific requirements here.',
      'uploaded': 'Uploaded',
      'missing': 'Missing',
      'neededByPrograms': 'Needed by {count} programs',
      'uploadingPercent': 'Uploading {percent}%',
      'replace': 'Replace',
      'upload': 'Upload',
      'aiReviewShort': 'AI Review',
      'generate': 'Generate',
      'notProvided': 'Not provided',
      'university': 'University',
      'downloading': 'Downloading',
      'analyzingWithAi': 'Analyzing with AI',
      'savingFeedback': 'Saving feedback',
      'done': 'Done!',
      'aiReviewAllDocuments': 'AI Review All Documents',
      'finalizing': 'Finalizing...',
      'couldNotAccessFile': 'Could not access file path',
      'uploadFailed': 'Upload failed: ',
      'mastersProgram': "Master's Program",
      'downloadingDocument': 'Downloading document...',

      // Deadline Calendar
      'deadlineCalendarEmpty': 'No deadlines on this day',
      'selectDateToSeeDeadlines': 'Select a date to see deadlines',

      // Dashboard / Pipeline
      'upcomingDeadlinesShort': 'Upcoming\nDeadlines',
      'appliedShort': 'Applied',

      // Search / Compare
      'matchingPrograms': '{count} Matching Programs',
      'compareSelected': '{count} selected — tap Compare to view side-by-side',
      'compareButton': 'Compare {count} Universities',
      'resultsCount': '{count} ',

      // Paywall
      'paymentError': 'Payment error',

      // IELTS/TOEFL required fix
      'ieltsToeflRequired': 'IELTS/TOEFL Required',

      // Forgot Password
      'forgotPasswordSubtitle': "No worries. Enter your email and we'll send you\na password reset link.",
      'sendResetLink': 'Send Reset Link →',
      'rememberYourPassword': 'Remember your password? ',

      // Reset Password
      'resetPasswordSubtitle': 'Create a new strong password to\nsecure your account.',
      'newPassword': 'New Password',
      'passwordRequirements': '✓ 8+ characters\n✓ One number\n✓ One special character',
      'passwordResetSuccess': 'Password has been reset successfully!',

      // Verify Email
      'verifyEmail': 'Verify Email',
      'verificationCodeSent': "We've sent a verification code to\n{email}",
      'didntReceiveCode': "Didn't receive the code?",
      'resendIn': 'Resend in ',
      'verifyCode': 'Verify Code →',
      'emailVerifiedSuccess': 'Email verified successfully!',

      // Login
      'biometricLoginEnabled': 'Biometric login enabled',
      'enableBiometric': 'Enable fingerprint / face unlock',
      'continueWithGoogle': 'Continue with Google',

      // Home
      'visitSettingsToComplete': 'Visit Settings to Complete Your Profile',

      // Email Tracking
      'providerConnected': '{provider} connected!',
      'failedToConnect': 'Failed to connect: ',
      'syncCompleted': 'Sync completed',
      'syncNow': 'Sync now',
      'connectedAccounts': 'Connected Accounts',
      'noEmailAccounts': 'No email accounts connected',
      'connectEmailPrompt': 'Connect Gmail or Outlook to auto-detect\napplication status from your inbox.',
      'connectGmail': 'Connect Gmail',
      'connectOutlook': 'Connect Outlook',
      'recentDetections': 'Recent Detections',
      'noStatusChanges': 'No status changes yet',
      'syncEmailPrompt': 'Sync your email to check for\napplication status updates.',
      'unknown': 'Unknown',
      'detected': 'Detected: {status}',
      'noStatusDetected': 'No status detected',

      // Email Tracking Hint
      'emailTrackingHint': 'Your email is used ONLY to automatically detect application status updates from universities you have applied to.\n\nWe do NOT read your personal messages, contacts, or any other emails. Your data is encrypted and secure. This connection only monitors emails from university domains to keep your application dashboard up to date.\n\nYou can disconnect at any time with no risk to your account.',

      // Visa Guide
      'visaGuide': 'Visa & Pre-departure Guide',
      'visaSubtitle': 'Complete checklist with links',
      'preDepartureChecklist': 'Pre-departure Checklist',
      'completedOf': '{count} of {total} completed',
      'essentialSteps': 'Essential Steps',
      'visaTip': 'Keep all documents organized in a folder. Make digital backups of everything!',
      'stepCheckRequirements': 'Check Visa Requirements',
      'stepCheckRequirementsDesc': 'Determine if you need a German student visa based on your nationality. EU/EEA citizens do not need a visa. Check the DAAD and German embassy websites.',
      'stepPrepareDocuments': 'Prepare Required Documents',
      'stepPrepareDocumentsDesc': 'Valid passport, university admission letter, proof of financial resources (€11,208/year in blocked account), health insurance, passport photos, CV, and motivation letter.',
      'stepOpenBlockedAccount': 'Open a Blocked Account',
      'stepOpenBlockedAccountDesc': 'Open a blocked account (Sperrkonto) with a German bank or approved provider (Expatrio, Fintiba, Coracle). Deposit ~€11,208 to show financial proof.',
      'stepHealthInsurance': 'Get Health Insurance',
      'stepHealthInsuranceDesc': 'German student health insurance (~€110/month). Choose a public provider like TK, AOK, or private options for EU citizens. Must be valid for visa application.',
      'stepBookAppointment': 'Book Visa Appointment',
      'stepBookAppointmentDesc': 'Schedule an appointment at the German embassy/consulate in your country. Wait times can be 2-12 weeks — book early!',
      'stepAttendInterview': 'Attend Visa Interview',
      'stepAttendInterviewDesc': 'Bring all original + 2 copies of documents. Be prepared to explain your study plans, finances, and post-graduation intentions. Interview is typically 10-15 minutes.',
      'stepWaitProcessing': 'Wait for Processing',
      'stepWaitProcessingDesc': 'Normal processing: 4-12 weeks. Avoid making non-refundable travel arrangements until approved. You can track status online in some countries.',
      'stepAnmeldung': 'Register in Germany (Anmeldung)',
      'stepAnmeldungDesc': 'Within 14 days of arrival, register your address at the local Bürgeramt. Required for bank account, phone contract, and residence permit.',
      'stepResidencePermit': 'Apply for Residence Permit',
      'stepResidencePermitDesc': 'Visit the Ausländerbehörde within 90 days to convert your student visa to a residence permit. Bring registration certificate, passport, insurance, and proof of enrollment.',
      'stepBankAccount': 'Open German Bank Account',
      'stepBankAccountDesc': 'With Anmeldung and residence permit, open a regular German bank account (N26, Deutsche Bank, Commerzbank). Easier for daily transactions than block account.',
      'daadVisaInfo': 'DAAD Visa Info',
      'documentChecklist': 'Document Checklist',
      'expatrioBlockedAccount': 'Expatrio Blocked Account',
      'tkStudentInsurance': 'TK Student Insurance',
      'germanMissions': 'German Missions',
      'berlinAnmeldung': 'Berlin Anmeldung',
      'learnMore': 'Learn more',

      // Gamification
      'achievements': 'Achievements',
      'achievementsSubtitle': 'Earn badges as you progress',
      'badgesEarned': '{earned} / {total} Badges Earned',
      'percentComplete': '{percent}% Complete',
      'yourStats': 'Your Stats',
      'allBadges': 'All Badges',
      'documents': 'Documents',

      // Admission Analysis
      'yourProfileMatch': 'Your Profile Match',
      'majorMatch': 'Major Match',
      'gpaMatch': 'GPA Match',
      'languagePref': 'Language Pref',
      'overallMatch': 'Overall Match',

      // Premium Match
      'admissionChanceEval': 'Admission Chance Evaluation',
      'academicMatch': 'Academic Match',
      'aiPremium': 'AI Premium (20%)',
      'unlockRemaining': 'Want to unlock the remaining 20%?',
      'optimizeCvSop': 'Optimize your CV & SOP via our AI Tailoring service to match this program.',

      // UniPass AI
      'uniPassAi': 'UniPass AI',
      'usesLeft': '{name} • {count} uses left',
      'chipAdmissionReq': 'Admission Requirements',
      'chipDeadlineIntake': 'Deadline & Intake',
      'chipRequiredDocs': 'Required Documents',
      'chipImproveMatch': 'Improve Match Score',
      'aiQueriesUsed': "You've used all your free AI queries this month.",
      'upgradePremium': 'Upgrade to Premium for unlimited access.',
      'hiImUniPassAi': "Hi! I'm UniPass AI",
      'aiWelcomeMsg': 'I can help you with everything about {name}. Ask me about admission requirements, deadlines, documents, or how to improve your match score!',
      'aiErrorTryAgain': 'Sorry, I encountered an error. Please try again.',
      'askAboutUni': 'Ask about {name}...',

      // University Stats
      'aboutUniversity': 'About the University',
      'uniIsLeading': '{name} is one of Europe\'s leading research universities.',
      'qsRanking': 'QS Ranking',
      'na': 'N/A',
      'reviews': 'Reviews',
      'students': 'Students',
      'employment': 'Employment',

      // Program Card
      'viewProgramWebsite': 'View Program Website',

      // Description
      'aboutProgram': 'About Program',
      'noDescriptionAvailable': 'No description available for this university program.',

      // AI Improvement
      'aiSuggestions': 'AI Suggestions',
      'analyzingProfile': 'Analyzing your profile...',
      'profileWellOptimized': 'Your profile is already well-optimized!',
      'suggestion': 'Suggestion',

      // AI Document Review
      'documentReview': 'Document Review',
      'reviewingDocuments': 'Reviewing your documents...',
      'noDocsToReview': 'No documents to review. Upload your documents first!',
      'generateCvWithAi': 'Generate CV with AI',
      'generateSopWithAi': 'Generate SOP with AI',

      // German Assistant
      'germanTutor': 'German Tutor',
      'germanTutorSubtitle': 'Practice German with AI',
      'practiceGerman': 'Practice your German',
      'writeInGerman': 'Write in German...',

      // AI Match
      'aiUniversityMatch': 'AI University Match',
      'aiMatchSubtitle': 'Personalized recommendations from AI',
      'completeProfileFirst': 'Complete your profile to get matches',
      'couldNotLoadRecommendations': 'Could not load recommendations',
      'yourTopMatches': 'Your Top Matches',
      'tapCheckmarkToSave': 'Tap the checkmark to save a program to your Pipeline',
      'removedFromPipeline': 'Removed from Pipeline',
      'addedToPipeline': 'Added to Pipeline',
      'addToPipeline': 'Add to Pipeline',
      'showLess': 'Show less',
      'showMore': 'Show more',
      'deadlineLabel': 'Deadline: {date}',

      // Comparison
      'selectUniversitiesToCompare': 'Select universities to compare',
      'logo': 'Logo',
      'ranking': 'Ranking',
      'programs': 'Programs',
      'status': 'Status',
      'deadlines': 'Deadlines',
      'applicationFee': 'Application Fee',

      // Application Detail Sheet
      'application': 'Application',
      'portalStatus': 'Portal Status',
      'autoTrack': 'Auto Track',
      'autoTrackDesc': 'Automatically sync portal status',
      'openPortalLink': 'Open Portal Link',
      'generateCvSopAiDetail': 'Generate CV/SOP with AI',

      // Application Timeline
      'applicationTimeline': 'Application Timeline',
      'timelineSubtitle': 'Track deadlines per university',
      'saveUniversitiesFirstTimeline': 'Save universities first to see your timeline',

      // Pipeline Card
      'generalTrack': 'General Track',
      'master': 'Master',
      'noDeadlineFallback': 'No Deadline',

      // Onboarding GPA
      'academicInformation': 'Academic Information',
      'valueCannotBeNegative': 'Value cannot be negative',
      'valueMustBeMax': 'Value must be ≤ {max} for {scale}',
      'yes': 'Yes',
      'no': 'No',
      'egHint': 'e.g. {value}',

      // Splash
      'findingUniversities': 'Finding suitable universities...',
      'loadingProfile': 'Loading your profile...',
      'preparingRecommendations': 'Preparing recommendations...',

      // Match Score
      'excellentChance': 'Excellent Chance',
      'fairChance': 'Fair Chance',
      'needsImprovement': 'Needs Improvement',
      'yourMatchScore': 'Your Match Score',
      // German Certificate
      'germanCertTitle': 'German Language Certificate',
      'germanCertDesc': 'Select your German certificate type and level',
      'addGermanCert': 'Add German Certificate',
      'certificateType': 'Certificate Type',
      'cefrLevel': 'CEFR Level',
      'removeGermanCert': 'Remove German Certificate',

      // Search
      'showPrograms': 'Show {count} Available Programs',
      'selectedCompare': '{count} selected — tap Compare to view side-by-side',
      'showEnglishTest': 'Show programs requiring English test',
      'moiSupport': 'Medium of Instruction certificate support',

      // Admin
      'adminTitle': 'UniPath Admin',
      'adminUsers': 'Users',
      'adminUniversities': 'Universities',
      'adminPrograms': 'Programs',
      'adminApplications': 'Applications',
      'adminDocuments': 'Documents',
      'adminSettings': 'Settings',
      'accessDenied': 'Access denied. Admin privileges required.',
      'myProfile': 'My Profile',

      'gpaLabel': 'GPA: ',
      'majorLabel': 'Major: ',
      'degreeLabel': 'Degree: ',
      'ieltsLabel': 'IELTS: ',
      'toeflLabel': 'TOEFL: ',
      'moiLabel': 'MOI: ',
      'countryLabel': 'Country: ',
      'targetLabel': 'Target: ',
      'profileTrack': 'Track',

      // Admin screen keys
      'actions': 'Actions',
      'addUniversity': 'Add University',
      'addProgram': 'Add Program',
      'deleteConfirm': 'Are you sure? This cannot be undone.',
      'exportCsv': 'Export CSV',
      'loadMore': 'Load More',
      'searchHint': 'Search by name or email...',
      'noUsers': 'No users yet',
      'noUniversities': 'No universities yet',
      'noApplications': 'No applications yet',
      'noPrograms': 'No programs yet',
      'noResults': 'No results found',
      'deleteWarning': 'This will also delete all associated programs.',
      'promoteAdmin': 'Grant admin privileges to',
      'revokeAdmin': 'Revoke admin privileges from',
      'userUpdated': 'User updated',
      'userDeleted': 'User deleted',
      'programUpdated': 'Program updated',
      'programDeleted': 'Program deleted',
      'universityUpdated': 'University updated',
      'universityDeleted': 'University deleted',
      'applicationUpdated': 'Application updated',
      'applicationDeleted': 'Application deleted',
      'failedToLoad': 'Failed to load: {error}',
      'universityName': 'University Name',
      'programName': 'Program Name',
      'rank': 'Ranking',
      'website': 'Website URL',
      'city': 'City',
      'requiredGpa': 'Required GPA',
      'tuitionFee': 'Tuition Fee / Year',
      'dataSource': 'Data Source',
      'programUrl': 'Program URL',
      'duration': 'Duration',
      'editUser': 'Edit User',
      'editUniversity': 'Edit University',
      'editProgram': 'Edit Program',
      'editApplication': 'Edit Application',
      'userRole': 'User',
      'adminRole': 'Admin',
      'userID': 'User ID',
      'universityID': 'University ID',
      'programID': 'Program ID',
      'appName': 'App Name',
      'version': 'Version',
      'supabaseProject': 'Supabase Project',
      'environment': 'Environment',
      'databaseOverview': 'Database Overview',
      'totalUsers': 'Total Users',
      'totalUniversities': 'Total Universities',
      'totalApplications': 'Total Applications',
      'quickInfo': 'Quick Info',
      'adminDescription': 'This admin panel manages all data in the UniPath Supabase database. Changes made here are reflected immediately.',
      'appConfig': 'App Configuration',
      'portalUrl': 'Portal URL',
      'paymentStatus': 'Payment Status',
      'role': 'Role',
      'countryField': 'Country',
      'selectUniversity': 'Select a university',
      'quickActions': 'Quick Actions',
      'recentActivity': 'Recent Activity',
      'noRecentActivity': 'No recent activity',
      'welcomeAdmin': 'Welcome back, Admin',

      // Onboarding
      'germany': 'Germany',

      // My Applications
      'error': 'Error: ',
    },
    'ar': {
      'appTitle': 'يوني باث',
      'home': 'الرئيسية',
      'search': 'بحث',
      'applications': 'الطلبات',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'accountSettings': 'إعدادات الحساب',
      'darkMode': 'الوضع الليلي',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'save': 'حفظ',
      'edit': 'تعديل',
      'cancel': 'إلغاء',
      'deleteAccount': 'حذف الحساب',
      'deleteAccountWarning':
          'هل أنت متأكد؟ لا يمكن التراجع عن هذا الإجراء.',
      'yesDelete': 'نعم، احذف',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'gpa': 'المعدل',
      'nationality': 'الجنسية',
      'preferredCities': 'المدن المفضلة',
      'budgetRange': 'نطاق الميزانية',
      'notifications': 'الإشعارات',
      'deadlineReminders': 'تذكيرات المواعيد',
      'generalNotifications': 'الإشعارات العامة',
      'profileCompleteness': 'اكتمال الملف',
      'matchScore': 'نسبة التطابق',
      'goodChance': 'فرصة جيدة',
      'strongMatch': 'تطابق قوي',
      'fairMatch': 'تطابق متوسط',
      'weakMatch': 'تطابق ضعيف',
      'notRecommended': 'غير موصى به',
      'excellentMatch': 'تطابق ممتاز',
      'recommendedForYou': 'موصى به لك',
      'seeAll': 'عرض الكل',
      'findPrograms': 'البحث عن برامج',
      'aiAdvisor': 'المستشار الذكي',
      'sopAssistant': 'مساعد البيان الشخصي',
      'cvBuilder': 'بناء السيرة الذاتية',
      'noIelts': 'بدون آيلتس',
      'englishProgram': 'برنامج إنجليزي',
      'tuition': 'الرسوم',
      'location': 'الموقع',
      'intake': 'موعد التقديم',
      'degree': 'الدرجة العلمية',
      'major': 'التخصص',
      'languageOfInstruction': 'لغة التدريس',
      'ielts': 'آيلتس',
      'toefl': 'توفل',
      'moi': 'شهادة اللغة',
      'uploadDocuments': 'رفع المستندات',
      'aiReview': 'مراجعة المستندات بالذكاء الاصطناعي',
      'aiTips': 'نصائح التحسين بالذكاء الاصطناعي',
      'remainingUses': 'الاستخدامات المتبقية:',
      'premiumFeature': 'ميزة مدفوعة',
      'premiumDescription': 'هذه ميزة مدفوعة. يرجى ترقية باقتك.',
      // 'goToPayment': 'اذهب للدفع', // removed - no payment screen
      'settingsSaved': 'تم حفظ الإعدادات بنجاح!',
      'noDocuments': 'لم يتم رفع أي مستندات بعد',
      'checkRequirements': 'تفقد قسم المتطلبات أعلاه',
      'overBudget': 'فوق الميزانية',
      'withinBudget': 'ضمن الميزانية',
      'preferredCity': 'المدينة المفضلة',
      'personalInfo': 'المعلومات الشخصية',
      'academicProfile': 'الملف الأكاديمي',
      'preferences': 'التفضيلات',
      'languageCertificate': 'شهادة اللغة',
      'appSettings': 'إعدادات التطبيق',
      'fieldOfStudy': 'مجال الدراسة',
      'degreeLevel': 'المستوى الدراسي',
      'studyLanguage': 'لغة الدراسة',
      'targetIntake': 'موعد التقديم',
      'gpaScale': 'مقياس المعدل',
      'all': 'الكل',
      'saved': 'محفوظ',
      'preparing': 'قيد التحضير',
      'applied': 'مقدم',
      'waiting': 'قيد الانتظار',
      'accepted': 'مقبول',
      'deadline': 'آخر موعد',
      'docs': 'المستندات',
      'chance': 'الفرصة',
      'expired': 'منتهي',
      'today': 'اليوم',
      'inDays': 'بعد %d أيام',
      'viewDetails': 'عرض التفاصيل',
      'searchPrograms': 'ابحث عن برامج أو جامعات...',
      'studyInGermany': 'ادرس في ألمانيا',
      'upcomingDeadlines': 'المواعيد القادمة',
      'yourMatchAverage': 'متوسط التطابق',
      'inTheNext30Days': 'في الـ 30 يوماً القادمة',
      'high': 'عالية',
      'medium': 'متوسطة',
      'requirementsChecklist': 'قائمة المتطلبات',
      'close': 'إغلاق',
      'noApplicationsFound': 'لا توجد طلبات',
      'programsMatch': 'برنامج تطابق ملفك',
      'loadingMore': 'جارٍ التحميل...',
      'seenAllPrograms': 'لقد رأيت جميع البرامج المتاحة!',
      'universitiesFound': 'جامعة موجودة',
      'retry': 'إعادة المحاولة',
      'searchForCourses': 'ابحث عن courses أو جامعات...',
      'filters': 'تصفية',
      'clearAll': 'مسح الكل',
      'ieltsRequired': 'مطلوب آيلتس',
      'moiAccepted': 'مقبول شهادة لغة',
      'maxTuitionPerYear': 'الحد الأقصى للرسوم / سنة',
      'instructionLanguage': 'لغة التدريس',
      'locationCity': 'الموقع / المدينة',
      'allLocations': 'جميع المواقع',
      'logout': 'تسجيل الخروج',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'welcomeBack': 'مرحباً بعودتك!',
      'loginSubtitle': 'سجل الدخول لمواصلة رحلة دراستك في الخارج',
      'emailOrUsername': 'البريد الإلكتروني أو اسم المستخدم',
      'enterEmailOrUsername': 'الرجاء إدخال البريد الإلكتروني أو اسم المستخدم',
      'enterPassword': 'الرجاء إدخال كلمة المرور',
      'passwordMinLength': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'rememberMe': 'تذكرني',
      'or': 'أو',
      'noAccount': 'ليس لديك حساب؟ ',
      'createAccount': 'إنشاء حساب',
      'registerSubtitle': 'انضم إلى يوني باث لتحقيق أحلامك في ألمانيا.',
      'username': 'اسم المستخدم',
      'enterUsername': 'الرجاء إدخال اسم المستخدم',
      'usernameMinLength': 'يجب أن يكون اسم المستخدم 3 أحرف على الأقل',
      'phoneOptional': 'الهاتف (اختياري)',
      'enterEmailAddress': 'الرجاء إدخال عنوان البريد الإلكتروني',
      'enterValidEmail': 'الرجاء إدخال بريد إلكتروني صحيح',
      'enterPasswordRegister': 'الرجاء إدخال كلمة المرور',
      'passwordMinLengthRegister': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'confirmPassword': 'تأكيد كلمة المرور',
      'confirmYourPassword': 'الرجاء تأكيد كلمة المرور',
      'passwordsNotMatch': 'كلمة المرور غير متطابقة',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟ ',
      'overview': 'نظرة عامة',
      'curriculum': 'المنهج',
      'checklist': 'قائمة المتطلبات',
      'notes': 'ملاحظات',
      'free': 'مجاني',
      'nonRefundable': 'غير قابل للاسترداد',
      'freeProgram': 'برنامج مجاني',
      'perYear': 'في السنة',
      'noDeadline': 'لا يوجد موعد',
      'notAvailable': 'غير متاح',
      'descriptionPlaceholder': 'الوصف التفصيلي عن الجامعة سيكون متاحاً قريباً.',
      'readMore': 'اقرأ المزيد',
      'programCurriculum': 'المنهج الدراسي',
      'noDetails': 'لا توجد تفاصيل',
      'noCurriculumData': 'لا توجد بيانات منهج.',
      'filterAiRecommended': 'تصفية المسارات الموصى بها بالذكاء الاصطناعي لملفك',
      'askUniPathAi': 'اسأل يوني باث',
      'welcomeTitle': 'دعنا نخصص\nتجربتك',
      'welcomeSubtitle':
          'سنطرح عليك بعض الأسئلة للعثور على أفضل الجامعات والبرامج المناسبة لك.',
      'intakeHeading': 'متى تريد أن\nتبدأ الدراسة؟',
      'studyLevelHeading': 'ما المستوى الدراسي\nالذي تبحث عنه؟',
      'studyLevelSubtitle': 'يمكنك اختيار الدرجة المستهدفة',
      'majorHeading': 'اختر تخصصك\nالدراسي',
      'majorSubtitle': 'اختر المجال الذي يتناسب مع خلفيتك الأكاديمية',
      'langHeading': 'تفضيل\nاللغة',
      'langSubtitle': 'اختر اللغة التي ترغب في الدراسة بها.',
      'ieltsHeading': 'اختبار اللغة\nالإنجليزية',
      'ieltsSubtitle': 'ما هو اختبار اللغة الإنجليزية الذي لديك؟',
      'ieltsScoreHeading': 'ما هي درجة\nالآيلتس الإجمالية لديك؟',
      'ieltsScoreSubtitle': 'اسحب الشريط لمطابقة درجة شهادتك',
      'moiHeading': 'تأكيد شهادة اللغة',
      'moiSubtitle':
          'هل تؤكد أن تعليمك السابق كان باللغة الإنجليزية بالكامل؟',
      'moiConfirmYes': 'نعم، أؤكد',
      'moiConfirmYesSub': 'دراستي كانت باللغة الإنجليزية بالكامل',
      'moiConfirmNo': 'لا، عد للخلف',
      'moiConfirmNoSub': 'اختيار خيار آخر',
      'tokenHeading': 'رمز التوثيق',
      'tokenSubtitle': 'أدخل رمز التوثيق إذا كان لديك (اختياري)',
      'tokenLabel': 'الرمز (اختياري)',
      'tokenHint': 'أدخل الرمز هنا...',
      'noneHeading': 'لا توجد شهادة لغة',
      'noneSubtitle':
          'لقد اخترت أنه ليس لديك شهادة لغة إنجليزية. بعض البرامج قد تتطلب واحدة.',
      'noneNote': 'ملاحظة',
      'noneNoteBody':
          'لا يزال بإمكانك التقدم للبرامج التي لا تتطلب شهادات لغة إنجليزية أو تقبل MOI.',
      'gpaHeading': 'أدائك\nالأكاديمي',
      'gpaSubtitle': 'أدخل معدلك التراكمي أو النسبة المئوية',
      'gpaScaleLabel': 'نظام مقياس المعدل',
      'gpaEarnedLabel': 'المعدل / الدرجة',
      'gpaHint4': 'أدخل قيمة بين 0.0 و 4.0',
      'gpaHint5': 'أدخل قيمة بين 0.0 و 5.0',
      'gpaHint100': 'أدخل النسبة المئوية الإجمالية (0 - 100)',
      'budgetHeading': 'ما هي ميزانية\nالرسوم الدراسية سنوياً؟',
      'budgetSubtitle': 'اختر الحد الأقصى للرسوم الذي يمكنك تحمله',
      'goalsHeading': 'ما هي أهدافك\nالدراسية الأساسية؟',
      'goalsSubtitle': 'اختر كل ما ينطبق على خططك المستقبلية',
      'btnGetStarted': 'لنبدأ \u2192',
      'btnLooksGood': 'يبدو جيداً! \u2192',
      'btnContinue': 'متابعة',
      'valIntake': 'الرجاء اختيار موعد بدء الدراسة',
      'valStudyLevel': 'الرجاء اختيار المستوى الدراسي',
      'valMajor': 'الرجاء اختيار مجال الاهتمام',
      'valLanguage': 'الرجاء اختيار تفضيل اللغة',
      'valTestType': 'الرجاء اختيار اختبار اللغة الإنجليزية',
      'valScore': 'الرجاء إدخال درجة الاختبار',
      'valGpa': 'الرجاء إدخال المعدل',
      'valGpaScale': 'الرجاء اختيار مقياس المعدل',
      'valMoiConfirm': 'الرجاء تأكيد أن لديك خطاب MOI',
      'valBudget': 'الرجاء اختيار نطاق الميزانية',
      'notesSaved': 'تم حفظ الملاحظات بنجاح!',
      'errorSavingNotes': 'خطأ في حفظ الملاحظات',
      'monthlyLimitReached': 'لقد وصلت للحد الشهري (10 استخدامات). قم بالترقية للاستخدام غير المحدود!',
      // 'paymentComingSoon': 'شاشة الدفع قريباً', // removed
      'noDocumentsUploaded': 'لم يتم رفع أي مستندات بعد. قم برفع مستنداتك من قائمة المتطلبات أعلاه (كشف الدرجات، السيرة الذاتية، بيان الغرض، الشهادة).',
      'profileDataNotLoaded': 'بيانات الملف الشخصي لم يتم تحميلها بعد. حاول مرة أخرى.',
      'comingSoon': 'قريباً',
      'welcomeAccountCreated': 'تم إنشاء الحساب بنجاح! مرحباً بك في يوني باث!',
      'welcomeBackLogin': 'مرحباً بعودتك! تم تسجيل الدخول بنجاح.',
      'loggedOutSuccess': 'تم تسجيل الخروج بنجاح!',
      'uploadDescription': 'الملفات التي يتم رفعها هنا ستُستخدم تلقائياً في جميع طلبات التقديم للجامعات الألمانية.',
      'starting': 'جارٍ البدء...',
      'downloadLabel': 'جارٍ التحميل',
      'analyzeLabel': 'جارٍ التحليل',
      'recommendationsLabel': 'جارٍ الحصول على التوصيات لـ',
      'cachedLabel': 'مخبأ',
      'downloadTimedOut': 'انتهت مهلة التحميل. تحقق من اتصالك بالإنترنت.',
      'serverReturned': 'الخادم أرجع {code}. حاول مرة أخرى لاحقاً.',
      'couldNotDownload': 'تعذر تحميل الملف. تحقق من اتصالك.',
      'aiFailed': 'فشل تحليل الذكاء الاصطناعي: {error}',
      'uploadThisDoc': 'قم برفع هذا المستند للحصول على تقييم محدد.',
      'reviewFailed': 'فشلت مراجعة المستندات. تحقق من اتصالك.',
      'uploadDocumentTitle': 'رفع مستند',
      'pdfFile': 'ملف PDF',
      'pdfSubtitle': 'اختر PDF من جهازك (الحد الأقصى 10 ميجابايت)',
      'gallery': 'المعرض',
      'gallerySubtitle': 'اختر صورة من معرض الصور',
      'camera': 'الكاميرا',
      'cameraSubtitle': 'التقط صورة للمستند',
      'fileTooLarge': 'الملف كبير جداً. الحد الأقصى 20 ميجابايت.',
      'resetPassword': 'إعادة تعيين كلمة المرور',
      'send': 'إرسال',
      'passwordResetSent': 'تم إرسال بريد إعادة تعيين كلمة المرور! تحقق من بريدك الوارد.',
      'loginSuccess': 'مرحباً بعودتك!',
      'registerSuccess': 'تم إنشاء الحساب بنجاح!',
      'premium': 'بريميوم',
      'unlockPremium': 'فتح البريميوم',
      'monthly': 'شهري',
      'yearly': 'سنوي',
      'lifetime': 'مدى الحياة',
      'bestValue': 'أفضل قيمة',
      'restorePurchases': 'استعادة المشتريات',
      'payment': 'الدفع',
      'premiumActivated': 'تم تفعيل البريميوم بنجاح!',
      'paymentComingSoon': 'قريباً نظام الدفع!',
      'perMonthShort': '/شهر',
      'perYearShort': '/سنة',
      'oneTime': 'مرة واحدة',
      'savePercent': 'وفر {percent}%',
      'premiumFeatures': 'ميزات البريميوم',
      'aiReviewUnlimited': 'مراجعة المستندات بالذكاء الاصطناعي (غير محدود)',
      'aiImprovement': 'اقتراحات التحسين بالذكاء الاصطناعي',
      'premiumMatchScore': 'نسبة التطابق المميزة (20%)',
      'prioritySupport': 'دعم ذو أولوية',
      'unlimitedAiUses': 'استخدام غير محدود للذكاء الاصطناعي',
      'goPremium': 'اشتراك بريميوم',
      'youArePremium': 'أنت مشترك في البريميوم!',
      'premiumUntil': 'بريميوم حتى {date}',
      'unlocked': 'مفتوح',

      // Home AI Tips
      'strongProfile': 'ملف قوي',
      'strongProfileDesc': 'ملفك الشخصي ممتاز! ركز على تقديم مستندات قوية (سيرة ذاتية، بيان شخصي، كشوف درجات) لكل طلب.',
      'polishDocuments': 'حسّن مستنداتك',
      'polishDocumentsDesc': 'استخدم مولد المستندات بالذكاء الاصطناعي في صفحة كل برنامج لإنشاء سيرة ذاتية ورسائل تحفيز مخصصة.',
      'trackDeadlines': 'تتبع المواعيد النهائية',
      'trackDeadlinesDesc': 'فعّل تذكيرات المواعيد النهائية في الإعدادات لعدم تفويت أي فرصة تقديم.',
      'boostGpa': 'حسّن معدلك التراكمي',
      'boostGpaDesc': 'فكر في إعادة المواد أو إبراز الخبرات العملية ذات الصلة في بيانك الشخصي.',
      'languageCert': 'شهادة لغة',
      'languageCertDesc': 'تحسين درجة الآيلتس أو الحصول على شهادة MOI يضيف نقاطاً مهمة لنسبة التطابق.',
      'refineMajor': 'حدد تخصصك',
      'refineMajorDesc': 'زر الإعدادات لتحديد تخصصك بدقة أكبر للحصول على تطابق أفضل مع البرامج.',
      'completeProfile': 'أكمل ملفك الشخصي',
      'completeProfileDesc': 'ملفك غير مكتمل. إضافة المعدل، درجة الآيلتس، والتخصص المستهدف سيحسن التطابق بشكل كبير.',
      'getLanguageCertified': 'احصل على شهادة لغة',
      'getLanguageCertifiedDesc': 'معظم البرامج تتطلب آيلتس (6.0+) أو MOI. إضافة أي منهما يفتح 10-15 نقطة في نسبة التطابق.',
      'pickIntake': 'اختر موعد التقديم',
      'pickIntakeDesc': 'تحديد موعد التقديم المستهدف يساعد في إيجاد البرامج المتوافقة مع جدولك الزمني.',
      'profileNeeded': 'الملف الشخصي مطلوب',
      'profileNeededDesc': 'أكمل ملفك الأكاديمي في الإعدادات — المعدل، التخصص، المستوى الدراسي، وتفضيلات اللغة.',
      'explorePrograms': 'استكشف البرامج',
      'exploreProgramsDesc': 'استخدم علامة التبويب "بحث" لإيجاد البرامج. احفظ الم interessante منها لترى نسبة التطابق.',
      'visitSettings': 'زر الإعدادات',
      'visitSettingsDesc': 'أكمل جميع حقول الملف الشخصي لفتح اقتراحات الذكاء الاصطناعي المخصصة لكل برنامج.',

      // Profile screen
      'accountAndTools': 'الحساب والأدوات',
      'myDocuments': 'مستنداتي',
      'cvSopCertificates': 'السيرة الذاتية، البيان الشخصي والشهادات',
      'emailTracking': 'تتبع البريد الإلكتروني',
      'emailTrackingDesc': 'الكشف التلقائي عن حالة الطلب من البريد',
      'updateProfilePrefs': 'تحديث ملفك الشخصي وتفضيلاتك',
      'adminDashboard': 'لوحة التحكم',
      'adminDashboardDesc': 'إدارة المستخدمين، الجامعات والمزيد',
      'signOutOfUnipath': 'تسجيل الخروج من يوني باث',
      'confirmLogout': 'هل أنت متأكد من تسجيل الخروج؟',
      'couldNotLoadProfile': 'تعذر تحميل الملف الشخصي',
      'ensureLoggedIn': 'يرجى التأكد من تسجيل الدخول.',

      // Connectivity banner
      'noInternetConnection': 'لا يوجد اتصال بالإنترنت. بعض الميزات قد لا تعمل.',
      'slowConnection': 'اتصال بطيء. التحميل قد يستغرق وقتاً أطول.',
      'connectionRestored': 'تم استعادة الاتصال',

      // Requirements checklist
      'academicTranscripts': 'كشف الدرجات الأكاديمية',
      'bachelorCertificate': 'شهادة البكالوريوس',
      'sopMotivationLetter': 'البيان الشخصي / رسالة التحفيز',
      'cvResume': 'السيرة الذاتية',
      'languageCertOptional': 'شهادة لغة (آيلتس/توفل) — اختياري',
      'germanCert': 'شهادة لغة ألمانية (TestDaF, Goethe, DSH) — اختياري',

      // Payment / Paywall
      'pleaseSignInFirst': 'يرجى تسجيل الدخول أولاً',
      'checkingPaymentStatus': 'جارٍ التحقق من حالة الدفع...',
      'paymentDelayed': 'تم استلام الدفع ولكن التفعيل متأخر. سيتم التفعيل قريباً.',

      // AI Generator
      'links': 'روابط',
      'failedToGeneratePdf': 'فشل إنشاء PDF: {error}',
      'fillNameAndBackground': 'يرجى إدخال اسمك وخلفيتك.',
      'copiedToClipboard': 'تم النسخ إلى الحافظة!',
      'generateCvSopAi': 'إنشاء سيرة ذاتية / بيان شخصي بالذكاء الاصطناعي',
      'copy': 'نسخ',
      'downloadPdf': 'تحميل PDF',
      'replaceFile': 'استبدال الملف',
      'cvGenerated': 'تم إنشاء السيرة الذاتية',
      'motivationLetterGenerated': 'تم إنشاء رسالة التحفيز',

      // Comparison
      'compare': 'مقارنة',
      'compareUniversities': 'مقارنة الجامعات',
      'selectUniversities': 'اختر الجامعات للمقارنة',
      'feature': 'الميزة',
      'noDeadlines': 'لا توجد مواعيد نهائية في هذا اليوم',

      // Calendar
      'deadlineCalendar': 'تقويم المواعيد',
      'upcomingDeadlinesCount': 'المواعيد القادمة',

      // Templates
      'documentTemplates': 'قوالب المستندات',
      'cvTemplate': 'السيرة الذاتية - النمط الألماني',
      'motivationLetterTemplate': 'قالب رسالة التحفيز',
      'recommendationTemplate': 'طلب خطاب توصية',

      // Dashboard
      'avgMatch': 'نسبة التطابق',
      'byStatus': 'حسب الحالة',

      // Back
      'pressAgainToExit': 'اضغط مرة أخرى للخروج',

      // Cost of Living
      'costOfLiving': 'تكاليف المعيشة',
      'costOfLivingSubtitle': 'تقدير المصروفات الشهرية حسب المدينة',
      'costOfLivingEstimator': 'مقدر تكاليف المعيشة',
      'selectCity': 'اختر المدينة',
      'monthlyLivingExpenses': 'المصروفات الشهرية',
      'rent': 'الإيجار',
      'food': 'الطعام',
      'insurance': 'التأمين',
      'transport': 'المواصلات',
      'miscellaneous': 'متنوعات',
      'costBreakdown': 'تحليل التكاليف',
      'vsBlockedAccount': 'مقابل الحساب المحظور',
      'blockedAccount': 'الحساب المحظور',
      'blockedAccountInfoTitle': 'ما هو الحساب المحظور؟',
      'blockedAccountInfoBody': 'الحساب المحظور (Sperrkonto) مطلوب للحصول على تأشيرة الطالب. يجب إيداع ',
      'estMonthlyCosts': 'التكاليف الشهرية التقريبية',
      'remaining': 'المتبقي',
      'blockedAccountTitle': 'الحساب المحظور 2025/26',
      'blockedAccountDesc': 'تتطلب الحكومة الألمانية €{yearly}/سنة (€{monthly}/شهر) في حساب محظور (Sperrkonto) للحصول على تأشيرة الطالب. تختلف التكاليف حسب المدينة — اضبط ميزانيتك وفقاً لذلك.',
      'overBlockedAccount': 'زيادة عن الحساب المحظور',
      'remainingAfterExpenses': 'المتبقي بعد المصروفات',

      // Side nav
      'legal': 'قانوني',
      'dangerZone': 'منطقة الخطر',
      'loading': 'جارٍ التحميل...',

      // Settings screen additional
      'privacyPolicy': 'سياسة الخصوصية',
      'termsOfService': 'شروط الخدمة',
      'saving': 'جارٍ الحفظ...',
      'saveChanges': 'حفظ التغييرات',
      'accountDeletedSuccess': 'تم حذف الحساب بنجاح.',
      'failedToDeleteAccount': 'فشل حذف الحساب: ',
      'profileComplete': 'الملف مكتمل!',
      'completeProfileForBetterMatches': 'أكمل ملفك للحصول على تطابق أفضل',
      'scale': 'المقياس',
      'of': 'من',
      'haveYouStudiedUniversity': 'هل درست في جامعة من قبل؟',
      'academicAverage': 'المعدل الأكاديمي (معدل جامعتك الحالية)',
      'highSchoolScore': 'درجة الثانوية العامة (مثال: توجيهي / ثانوية عامة)',
      'iHaveIelts': 'لدي شهادة آيلتس',
      'enterScoreBelow': 'أدخل درجتك أدناه',
      'someProgramsRequireIt': 'بعض البرامج تتطلبها',
      'ieltsScoreEg': 'درجة الآيلتس (مثال 6.5)',
      'iHaveToefl': 'لدي شهادة توفل',
      'acceptedByManyUniversities': 'مقبول من قبل العديد من الجامعات الألمانية',
      'toeflScoreEg': 'درجة التوفل (مثال 90)',
      'moiConfirmToggle': 'شهادة اللغة (MOI)',
      'confirmedDegreeEnglish': 'تم التأكيد — الدراسة باللغة الإنجليزية',
      'confirmIfDegreeEnglish': 'أكد إذا كانت دراستك باللغة الإنجليزية',
      'enableNotifications': 'تفعيل الإشعارات',
      'receiveAllNotifications': 'استلام جميع أنواع الإشعارات',
      'getRemindedBeforeDeadlines': 'تذكير قبل مواعيد التقديم',
      'applicationUpdates': 'تحديثات الطلبات',
      'statusChanges': 'تغييرات الحالة (محفوظ → مقدم → مقبول/مرفوض)',
      'tipsNewProgramsAnnouncements': 'نصائح، برامج جديدة، وإعلانات',
      'xSelected': '{count} مختارة',
      'remindMeBeforeDeadline': 'تذكيري قبل الموعد النهائي',
      'day': 'يوم',
      'days': 'أيام',
      'quietHours': 'ساعات الهدوء',
      'start': 'البداية',
      'end': 'النهاية',
      'select': 'اختر',

      // Document Templates
      'cvGermanStyle': 'السيرة الذاتية - النمط الألماني',
      'cvTemplateSubtitle': 'تنسيق جدولي تفضله الجامعات الألمانية',
      'cvSectionPersonal': 'المعلومات الشخصية (الاسم، العنوان، الهاتف، البريد)',
      'cvSectionEducation': 'التعليم (ترتيب زمني عكسي)',
      'cvSectionWork': 'الخبرات العملية (إن وجدت)',
      'cvSectionSkills': 'المهارات واللغات',
      'cvSectionInterests': 'الاهتمامات والأنشطة',
      'cvSectionReferences': 'المراجع (اختياري)',
      'cvTip': 'اجعله موجزاً — حد أقصى صفحتين. استخدم تنسيق Europass أو السيرة الذاتية الجدولية.',
      'motivationLetterSubtitle': 'رسالة أكاديمية مخصصة للجامعات الألمانية',
      'mlSectionHeader': 'رأس الصفحة: معلوماتك + عنوان الجامعة + التاريخ',
      'mlSectionSubject': 'الموضوع: "رسالة تحفيز لبرنامج [اسم البرنامج]"',
      'mlSectionPara1': 'الفقرة 1: قدم نفسك + ما الذي تتقدم له',
      'mlSectionPara2': 'الفقرة 2: لماذا هذا البرنامج؟ اربط خلفيتك بالبرنامج',
      'mlSectionPara3': 'الفقرة 3: لماذا ألمانيا؟ أظهر معرفتك بنظام التعليم',
      'mlSectionPara4': 'الفقرة 4: أهدافك المستقبلية — كيف تتناسب هذه الدرجة مع خططك المهنية',
      'mlSectionClosing': 'الخاتمة: خاتمة واثقة + التوقيع',
      'mlTip': 'كن محدداً بشأن الجامعة والبرنامج. الرسائل العامة يتم اكتشافها بسهولة.',
      'recommendationSubtitle': 'بريد إلكتروني احترافي لطلب توصية من الأساتذة',
      'recSectionSubject': 'الموضوع: "طلب خطاب توصية — [اسمك]"',
      'recSectionGreeting': 'التحية: عزيزي البروفيسور [الاسم]،',
      'recSectionIntro': 'المقدمة: ذكرهم من أنت (المادة، الفصل الدراسي)',
      'recSectionRequest': 'الطلب: اطلب بأدب كتابة خطاب توصية',
      'recSectionDetails': 'التفاصيل: أرفق سيرتك الذاتية ودرجاتك وقائمة البرامج',
      'recSectionDeadline': 'الموعد النهائي: اذكر متى تحتاجه',
      'recSectionClosing': 'الخاتمة: اشكرهم + اعرض اللقاء شخصياً',
      'recTip': 'اطلب قبل 4 أسابيع على الأقل من الموعد النهائي. قدم جميع المواد مسبقاً.',
      'proTip': 'نصيحة احترافية',
      'aiGeneratorPrompt': 'استخدم مولد المستندات بالذكاء الاصطناعي لإنشاء سيرة ذاتية أو رسالة تحفيز مخصصة بناءً على ملفك. اذهب إلى أي صفحة جامعة واضغط "إنشاء سيرة ذاتية" أو "إنشاء رسالة تحفيز".',

      // Smart Document Hub
      'smartDocumentHub': 'مركز المستندات الذكي',
      'reviewing': 'جارٍ المراجعة...',
      'aiReviewAll': 'مراجعة الكل بالذكاء الاصطناعي',
      'documentReadiness': 'جاهزية المستندات',
      'acrossSavedUniversities': 'عبر {count} جامعة محفوظة',
      'noSavedUniversities': 'لا توجد جامعات محفوظة بعد',
      'saveUniversitiesFirst': 'احفظ الجامعات في مسار التقديم أولاً',
      'documentsShowRequirements': 'ستظهر المستندات متطلبات كل برنامج هنا.',
      'uploaded': 'مرفوع',
      'missing': 'مفقود',
      'neededByPrograms': 'مطلوب لـ {count} برامج',
      'uploadingPercent': 'جارٍ الرفع {percent}%',
      'replace': 'استبدال',
      'upload': 'رفع',
      'aiReviewShort': 'مراجعة AI',
      'generate': 'إنشاء',
      'notProvided': 'غير مزود',
      'university': 'جامعة',
      'downloading': 'جارٍ التحميل',
      'analyzingWithAi': 'جارٍ التحليل بالذكاء الاصطناعي',
      'savingFeedback': 'جارٍ حفظ التقييم',
      'done': 'تم!',
      'aiReviewAllDocuments': 'مراجعة جميع المستندات بالذكاء الاصطناعي',
      'finalizing': 'جارٍ الإنهاء...',
      'couldNotAccessFile': 'تعذر الوصول إلى مسار الملف',
      'uploadFailed': 'فشل الرفع: ',
      'mastersProgram': 'برنامج الماجستير',
      'downloadingDocument': 'جارٍ تحميل المستند...',

      // Deadline Calendar
      'deadlineCalendarEmpty': 'لا توجد مواعيد نهائية في هذا اليوم',
      'selectDateToSeeDeadlines': 'اختر تاريخاً لرؤية المواعيد النهائية',

      // Dashboard / Pipeline
      'upcomingDeadlinesShort': 'المواعيد\nالقادمة',
      'appliedShort': 'مقدم',

      // Search / Compare
      'matchingPrograms': '{count} برنامج مطابق',
      'compareSelected': '{count} مختارة — اضغط مقارنة للعرض جنباً إلى جنب',
      'compareButton': 'مقارنة {count} جامعات',
      'resultsCount': '{count} ',

      // Paywall
      'paymentError': 'خطأ في الدفع',

      // IELTS/TOEFL required fix
      'ieltsToeflRequired': 'مطلوب آيلتس/توفل',

      // Forgot Password
      'forgotPasswordSubtitle': 'لا تقلق. أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة تعيين كلمة المرور.',
      'sendResetLink': 'إرسال رابط إعادة التعيين ←',
      'rememberYourPassword': 'تتذكر كلمة المرور الخاصة بك؟ ',

      // Reset Password
      'resetPasswordSubtitle': 'أنشئ كلمة مرور قوية جديدة لتأمين حسابك.',
      'newPassword': 'كلمة المرور الجديدة',
      'passwordRequirements': '✓ 8 أحرف أو أكثر\n✓ رقم واحد على الأقل\n✓ حرف خاص واحد على الأقل',
      'passwordResetSuccess': 'تم إعادة تعيين كلمة المرور بنجاح!',

      // Verify Email
      'verifyEmail': 'تأكيد البريد الإلكتروني',
      'verificationCodeSent': 'لقد أرسلنا رمز التحقق إلى\n{email}',
      'didntReceiveCode': 'لم يصلك الرمز؟',
      'resendIn': 'إعادة الإرسال بعد ',
      'verifyCode': 'تأكيد الرمز ←',
      'emailVerifiedSuccess': 'تم تأكيد البريد الإلكتروني بنجاح!',

      // Login
      'biometricLoginEnabled': 'تم تفعيل تسجيل الدخول البيومتري',
      'enableBiometric': 'تفعيل بصمة الإصبع / فتح الوجه',
      'continueWithGoogle': 'المتابعة مع Google',

      // Home
      'visitSettingsToComplete': 'زر الإعدادات لإكمال ملفك الشخصي',

      // Email Tracking
      'providerConnected': 'تم الاتصال بـ {provider}!',
      'failedToConnect': 'فشل الاتصال: ',
      'syncCompleted': 'تمت المزامنة',
      'syncNow': 'مزامنة الآن',
      'connectedAccounts': 'الحسابات المتصلة',
      'noEmailAccounts': 'لا توجد حسابات بريد إلكتروني متصلة',
      'connectEmailPrompt': 'قم بتوصيل Gmail أو Outlook للكشف التلقائي عن حالة الطلب من صندوق الوارد الخاص بك.',
      'connectGmail': 'توصيل Gmail',
      'connectOutlook': 'توصيل Outlook',
      'recentDetections': 'الاكتشافات الأخيرة',
      'noStatusChanges': 'لا توجد تغييرات في الحالة بعد',
      'syncEmailPrompt': 'قم بمزامنة بريدك الإلكتروني للتحقق من تحديثات حالة الطلب.',
      'unknown': 'غير معروف',
      'detected': 'تم الكشف: {status}',
      'noStatusDetected': 'لم يتم الكشف عن حالة',

      // Email Tracking Hint
      'emailTrackingHint': 'بريدك الإلكتروني يُستخدم فقط للكشف التلقائي عن تحديثات حالة الطلبات من الجامعات التي تقدمت إليها.\n\nنحن لا نقرأ رسائلك الشخصية أو جهات الاتصال أو أي رسائل أخرى. بياناتك مشفرة وآمنة. هذا الاتصال يراقب فقط رسائل الجامعات للحفاظ على تحديث لوحة الطلبات الخاصة بك.\n\nيمكنك قطع الاتصال في أي وقت دون أي خطر على حسابك.',

      // Visa Guide
      'visaGuide': 'دليل التأشيرة وما قبل المغادرة',
      'visaSubtitle': 'قائمة تحقق كاملة مع روابط',
      'preDepartureChecklist': 'قائمة ما قبل المغادرة',
      'completedOf': '{count} من {total} مكتملة',
      'essentialSteps': 'الخطوات الأساسية',
      'visaTip': 'احتفظ بجميع المستندات منظمة في مجلد. قم بعمل نسخ احتياطية رقمية لكل شيء!',
      'stepCheckRequirements': 'التحقق من متطلبات التأشيرة',
      'stepCheckRequirementsDesc': 'حدد ما إذا كنت بحاجة إلى تأشيرة طالب ألمانية بناءً على جنسيتك. مواطنو الاتحاد الأوروبي/المنطقة الاقتصادية الأوروبية لا يحتاجون إلى تأشيرة. تحقق من موقع DAAD وسفارة ألمانيا.',
      'stepPrepareDocuments': 'تجهيز المستندات المطلوبة',
      'stepPrepareDocumentsDesc': 'جواز سفر ساري المفعول، خطاب قبول جامعي، إثبات الموارد المالية (€11,208/سنة في حساب محظور)، تأمين صحي، صور جواز سفر، سيرة ذاتية، ورسالة تحفيز.',
      'stepOpenBlockedAccount': 'فتح حساب محظور',
      'stepOpenBlockedAccountDesc': 'افتح حساباً محظوراً (Sperrkonto) مع بنك ألماني أو مزود معتمد (Expatrio، Fintiba، Coracle). أودع ~€11,208 كإثبات مالي.',
      'stepHealthInsurance': 'الحصول على تأمين صحي',
      'stepHealthInsuranceDesc': 'تأمين صحي للطلاب الألمان (~€110/شهر). اختر مزوداً عاماً مثل TK أو AOK أو خيارات خاصة لمواطني الاتحاد الأوروبي. يجب أن يكون ساري المفعول لتقديم طلب التأشيرة.',
      'stepBookAppointment': 'حجز موعد التأشيرة',
      'stepBookAppointmentDesc': 'حدد موعداً في السفارة/القنصلية الألمانية في بلدك. أوقات الانتظار قد تكون 2-12 أسبوعاً — احجز مبكراً!',
      'stepAttendInterview': 'حضور مقابلة التأشيرة',
      'stepAttendInterviewDesc': 'أحضر جميع المستندات الأصلية + نسختين. كن مستعداً لشرح خططك الدراسية وماليتك ونواياك بعد التخرج. المقابلة عادة ما تكون 10-15 دقيقة.',
      'stepWaitProcessing': 'انتظار المعالجة',
      'stepWaitProcessingDesc': 'المعالجة العادية: 4-12 أسبوعاً. تجنب القيام بترتيبات سفر غير قابلة للاسترداد حتى تتم الموافقة.',
      'stepAnmeldung': 'التسجيل في ألمانيا (Anmeldung)',
      'stepAnmeldungDesc': 'في غضون 14 يوماً من الوصول، سجل عنوانك في مكتب Bürgeramt المحلي. مطلوب لفتح حساب بنكي وعقد هاتف وتصريح الإقامة.',
      'stepResidencePermit': 'التقدم بطلب للحصول على تصريح إقامة',
      'stepResidencePermitDesc': 'قم بزيارة Ausländerbehörde في غضون 90 يوماً لتحويل تأشيرة الطالب إلى تصريح إقامة. أحضر شهادة التسجيل وجواز السفر والتأمين وإثبات القبول.',
      'stepBankAccount': 'فتح حساب بنكي ألماني',
      'stepBankAccountDesc': 'بعد Anmeldung وتصريح الإقامة، افتح حساباً بنكياً ألمانياً عادياً (N26، Deutsche Bank، Commerzbank). أسهل للمعاملات اليومية من الحساب المحظور.',
      'daadVisaInfo': 'معلومات تأشيرة DAAD',
      'documentChecklist': 'قائمة المستندات',
      'expatrioBlockedAccount': 'حساب Expatrio المحظور',
      'tkStudentInsurance': 'تأمين TK الطلابي',
      'germanMissions': 'البعثات الألمانية',
      'berlinAnmeldung': 'تسجيل برلين',
      'learnMore': 'اعرف المزيد',

      // Gamification
      'achievements': 'الإنجازات',
      'achievementsSubtitle': 'احصل على شارات مع تقدمك',
      'badgesEarned': '{earned} / {total} شارات مكتسبة',
      'percentComplete': '{percent}% مكتمل',
      'yourStats': 'إحصائياتك',
      'allBadges': 'جميع الشارات',

      // Admission Analysis
      'yourProfileMatch': 'تطابق ملفك الشخصي',
      'majorMatch': 'تطابق التخصص',
      'gpaMatch': 'تطابق المعدل',
      'languagePref': 'تفضيل اللغة',
      'overallMatch': 'التطابق الإجمالي',

      // Premium Match
      'admissionChanceEval': 'تقييم فرصة القبول',
      'academicMatch': 'التطابق الأكاديمي',
      'aiPremium': 'البريميوم بالذكاء الاصطناعي (20%)',
      'unlockRemaining': 'هل تريد فتح الـ 20% المتبقية؟',
      'optimizeCvSop': 'قم بتحسين سيرتك الذاتية ورسالة التحفيز من خلال خدمة التخصيص بالذكاء الاصطناعي لتتناسب مع هذا البرنامج.',

      // UniPass AI
      'uniPassAi': 'يوني باس AI',
      'usesLeft': '{name} • {count} استخدام متبقي',
      'chipAdmissionReq': 'متطلبات القبول',
      'chipDeadlineIntake': 'الموعد النهائي وموعد التقديم',
      'chipRequiredDocs': 'المستندات المطلوبة',
      'chipImproveMatch': 'تحسين نسبة التطابق',
      'aiQueriesUsed': 'لقد استخدمت كل استعلامات الذكاء الاصطناعي المجانية لهذا الشهر.',
      'upgradePremium': 'قم بالترقية إلى البريميوم للاستخدام غير المحدود.',
      'hiImUniPassAi': 'مرحباً! أنا يوني باس AI',
      'aiWelcomeMsg': 'يمكنني مساعدتك في كل شيء عن {name}. اسألني عن متطلبات القبول أو المواعيد النهائية أو المستندات أو كيفية تحسين نسبة التطابق!',
      'aiErrorTryAgain': 'عذراً، حدث خطأ. يرجى المحاولة مرة أخرى.',
      'askAboutUni': 'اسأل عن {name}...',

      // University Stats
      'aboutUniversity': 'عن الجامعة',
      'uniIsLeading': '{name} هي واحدة من جامعات الأبحاث الرائدة في أوروبا.',
      'qsRanking': 'تصنيف QS',
      'na': 'غير متاح',
      'reviews': 'التقييمات',
      'students': 'الطلاب',
      'employment': 'التوظيف',

      // Program Card
      'viewProgramWebsite': 'عرض موقع البرنامج',

      // Description
      'aboutProgram': 'عن البرنامج',
      'noDescriptionAvailable': 'لا يوجد وصف متاح لهذا البرنامج الجامعي.',

      // AI Improvement
      'aiSuggestions': 'اقتراحات الذكاء الاصطناعي',
      'analyzingProfile': 'جارٍ تحليل ملفك الشخصي...',
      'profileWellOptimized': 'ملفك الشخصي محسّن بالفعل!',
      'suggestion': 'اقتراح',

      // AI Document Review
      'documentReview': 'مراجعة المستندات',
      'reviewingDocuments': 'جارٍ مراجعة مستنداتك...',
      'noDocsToReview': 'لا توجد مستندات للمراجعة. قم برفع مستنداتك أولاً!',
      'generateCvWithAi': 'إنشاء سيرة ذاتية بالذكاء الاصطناعي',
      'generateSopWithAi': 'إنشاء بيان شخصي بالذكاء الاصطناعي',

      // German Assistant
      'germanTutor': 'مدرس اللغة الألمانية',
      'germanTutorSubtitle': 'تدرب على الألمانية مع الذكاء الاصطناعي',
      'practiceGerman': 'تدرب على اللغة الألمانية',
      'writeInGerman': 'اكتب بالألمانية...',

      // AI Match
      'aiUniversityMatch': 'تطابق الجامعات بالذكاء الاصطناعي',
      'aiMatchSubtitle': 'توصيات مخصصة من الذكاء الاصطناعي',
      'completeProfileFirst': 'أكمل ملفك الشخصي للحصول على التطابقات',
      'couldNotLoadRecommendations': 'تعذر تحميل التوصيات',
      'yourTopMatches': 'أفضل التطابقات',
      'tapCheckmarkToSave': 'اضغط على علامة الصح لحفظ برنامج في مسار التقديم الخاص بك',
      'removedFromPipeline': 'تمت الإزالة من مسار التقديم',
      'addedToPipeline': 'تمت الإضافة إلى مسار التقديم',
      'addToPipeline': 'إضافة إلى مسار التقديم',
      'showLess': 'عرض أقل',
      'showMore': 'عرض المزيد',
      'deadlineLabel': 'آخر موعد: {date}',

      // Comparison
      'selectUniversitiesToCompare': 'اختر الجامعات للمقارنة',
      'logo': 'الشعار',
      'ranking': 'التصنيف',
      'programs': 'البرامج',
      'status': 'الحالة',
      'deadlines': 'المواعيد النهائية',
      'applicationFee': 'رسوم التقديم',

      // Application Detail Sheet
      'application': 'الطلب',
      'portalStatus': 'حالة البوابة',
      'autoTrack': 'تتبع تلقائي',
      'autoTrackDesc': 'مزامنة حالة البوابة تلقائياً',
      'openPortalLink': 'فتح رابط البوابة',
      'generateCvSopAiDetail': 'إنشاء سيرة ذاتية/بيان شخصي بالذكاء الاصطناعي',

      // Application Timeline
      'applicationTimeline': 'الجدول الزمني للطلبات',
      'timelineSubtitle': 'تتبع المواعيد النهائية لكل جامعة',
      'saveUniversitiesFirstTimeline': 'احفظ الجامعات أولاً لرؤية جدولك الزمني',

      // Pipeline Card
      'generalTrack': 'مسار عام',
      'master': 'ماجستير',
      'noDeadlineFallback': 'لا يوجد موعد نهائي',

      // Onboarding GPA
      'academicInformation': 'المعلومات الأكاديمية',
      'valueCannotBeNegative': 'لا يمكن أن تكون القيمة سالبة',
      'valueMustBeMax': 'يجب أن تكون القيمة ≤ {max} لـ {scale}',
      'yes': 'نعم',
      'no': 'لا',
      'egHint': 'مثال: {value}',

      // Splash
      'findingUniversities': 'جاري البحث عن الجامعات المناسبة...',
      'loadingProfile': 'جاري تحميل ملفك الشخصي...',
      'preparingRecommendations': 'جاري تحضير التوصيات...',

      // Match Score
      'excellentChance': 'فرصة ممتازة',
      'fairChance': 'فرصة متوسطة',
      'needsImprovement': 'بحاجة للتحسين',
      'yourMatchScore': 'نسبة التطابق الخاصة بك',
      // German Certificate
      'germanCertTitle': 'شهادة اللغة الألمانية',
      'germanCertDesc': 'اختر نوع شهادة الألمانية ومستواها',
      'addGermanCert': 'إضافة شهادة ألمانية',
      'certificateType': 'نوع الشهادة',
      'cefrLevel': 'المستوى',
      'removeGermanCert': 'إزالة شهادة الألمانية',

      // Search
      'showPrograms': 'عرض {count} برنامج متاح',
      'selectedCompare': 'تم اختيار {count} — اضغط مقارنة للعرض',
      'showEnglishTest': 'إظهار البرامج التي تتطلب اختبار إنجليزي',
      'moiSupport': 'دعم شهادة لغة التدريس',

      // Admin
      'adminTitle': 'يوني باث — المشرف',
      'adminUsers': 'المستخدمون',
      'adminUniversities': 'الجامعات',
      'adminPrograms': 'البرامج',
      'adminApplications': 'الطلبات',
      'adminDocuments': 'المستندات',
      'adminSettings': 'الإعدادات',
      'accessDenied': 'تم رفض الوصول. صلاحيات المشرف مطلوبة.',
      'myProfile': 'ملفي الشخصي',

      'gpaLabel': 'المعدل: ',
      'majorLabel': 'التخصص: ',
      'degreeLabel': 'الدرجة: ',
      'ieltsLabel': 'IELTS: ',
      'toeflLabel': 'TOEFL: ',
      'moiLabel': 'MOI: ',
      'countryLabel': 'البلد: ',
      'targetLabel': 'الهدف: ',
      'profileTrack': 'المسار',

      // Admin screen keys
      'actions': 'الإجراءات',
      'addUniversity': 'إضافة جامعة',
      'addProgram': 'إضافة برنامج',
      'deleteConfirm': 'هل أنت متأكد؟ لا يمكن التراجع عن هذا.',
      'exportCsv': 'تصدير CSV',
      'loadMore': 'تحميل المزيد',
      'searchHint': 'ابحث بالاسم أو البريد...',
      'noUsers': 'لا يوجد مستخدمون بعد',
      'noUniversities': 'لا توجد جامعات بعد',
      'noApplications': 'لا توجد طلبات بعد',
      'noPrograms': 'لا توجد برامج بعد',
      'noResults': 'لا توجد نتائج',
      'deleteWarning': 'سيتم حذف جميع البرامج المرتبطة.',
      'promoteAdmin': 'منح صلاحيات المشرف لـ',
      'revokeAdmin': 'إزالة صلاحيات المشرف من',
      'userUpdated': 'تم تحديث المستخدم',
      'userDeleted': 'تم حذف المستخدم',
      'programUpdated': 'تم تحديث البرنامج',
      'programDeleted': 'تم حذف البرنامج',
      'universityUpdated': 'تم تحديث الجامعة',
      'universityDeleted': 'تم حذف الجامعة',
      'applicationUpdated': 'تم تحديث الطلب',
      'applicationDeleted': 'تم حذف الطلب',
      'failedToLoad': 'فشل التحميل: {error}',
      'universityName': 'اسم الجامعة',
      'programName': 'اسم البرنامج',
      'rank': 'الترتيب',
      'website': 'رابط الموقع',
      'city': 'المدينة',
      'requiredGpa': 'المعدل المطلوب',
      'tuitionFee': 'الرسوم الدراسية / السنة',
      'dataSource': 'مصدر البيانات',
      'programUrl': 'رابط البرنامج',
      'duration': 'المدة',
      'editUser': 'تعديل المستخدم',
      'editUniversity': 'تعديل الجامعة',
      'editProgram': 'تعديل البرنامج',
      'editApplication': 'تعديل الطلب',
      'userRole': 'مستخدم',
      'adminRole': 'مشرف',
      'userID': 'معرف المستخدم',
      'universityID': 'معرف الجامعة',
      'programID': 'معرف البرنامج',
      'appName': 'اسم التطبيق',
      'version': 'الإصدار',
      'supabaseProject': 'مشروع Supabase',
      'environment': 'البيئة',
      'databaseOverview': 'نظرة عامة على قاعدة البيانات',
      'totalUsers': 'إجمالي المستخدمين',
      'totalUniversities': 'إجمالي الجامعات',
      'totalApplications': 'إجمالي الطلبات',
      'quickInfo': 'معلومات سريعة',
      'adminDescription': 'لوحة التحكم هذه تدير جميع بيانات قاعدة بيانات UniPath Supabase. التغييرات التي تتم هنا تنعكس فوراً.',
      'appConfig': 'إعدادات التطبيق',
      'portalUrl': 'رابط البوابة',
      'paymentStatus': 'حالة الدفع',
      'role': 'الدور',
      'countryField': 'البلد',
      'selectUniversity': 'اختر جامعة',
      'quickActions': 'إجراءات سريعة',
      'recentActivity': 'النشاط الأخير',
      'noRecentActivity': 'لا يوجد نشاط حديث',
      'welcomeAdmin': 'مرحباً بعودتك، أيها المشرف',

      // Onboarding
      'germany': 'ألمانيا',

      // My Applications
      'error': 'خطأ: ',
    },
  };

  String translate(String key) {
    return _localizedStrings[locale.languageCode]?[key] ?? key;
  }

  static Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations.load(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
